import AppKit
import ImageIO
import UniformTypeIdentifiers

/// The 素材库 panel, element portraits, 文件 › 导入… and 导出全书… through the
/// real AppKit controllers, tab host and Rust workspace, wired as
/// AppDelegate wires them. Every file is generated by the test: small PNG,
/// JPEG, PDF, Markdown, text and Word documents with synthetic content.
extension BindingAcceptance {
    private final class LibraryHarness {
        let directory: URL
        let sources: URL
        private(set) var workspace: LabWorkspaceCore
        let project: WorkspaceProject
        let chapter: WorkspaceChapter
        private(set) var window: NSWindow
        private(set) var host: MacChapterWorkspace
        private(set) var model: MaterialLibraryModel!
        private(set) var controller: MacMaterialLibraryViewController!
        private(set) var panelWindow: NSWindow!
        /// Answers the panel's alerts; nil cancels.
        var answer: ((NSAlert) -> NSApplication.ModalResponse)?
        var opened: [URL] = []
        var quickLooked: [[URL]] = []

        init() throws {
            let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
                .appendingPathComponent("apple-native-lab")
            self.directory = directory
            sources = directory.deletingLastPathComponent().appendingPathComponent("sources", isDirectory: true)
            try FileManager.default.createDirectory(at: sources, withIntermediateDirectories: true)
            let workspace = LabWorkspaceCore(directory: directory)
            self.workspace = workspace
            let listed: [WorkspaceProject] = try BindingAcceptance.elementResult { workspace.projects(completion: $0) }
            try BindingAcceptance.require(listed.isEmpty, "Library fixture was not isolated")
            project = try BindingAcceptance.elementResult { workspace.createProject(name: "素材库合成项目", completion: $0) }
            let projectID = project.id
            chapter = try BindingAcceptance.elementResult { workspace.createChapter(projectID: projectID, title: "雨夜", completion: $0) }
            (window, host) = BindingAcceptance.elementHost(workspace)
        }

        /// A new model and panel, as AppDelegate.showMaterials builds them.
        func openPanel() throws {
            panelWindow?.close()
            let model = MaterialLibraryModel(workspace: workspace, projectID: project.id)
            let host = self.host, projectID = project.id
            model.onLibrary = { library in host.applyMaterialLibrary(projectID: projectID, library: library) }
            host.onMaterialLibrary = { [weak model] id, library in
                if id == projectID, model?.busy == false { model?.apply(library, message: nil) }
            }
            let controller = MacMaterialLibraryViewController(model: model)
            controller.presentAlert = { [weak self] alert, done in
                alert.layout()
                done(self?.answer?(alert) ?? .alertSecondButtonReturn)
            }
            controller.openURL = { [weak self] url in self?.opened.append(url) }
            controller.onQuickLook = { [weak self] urls in self?.quickLooked.append(urls) }
            let panelWindow = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 420, height: 720),
                                       styleMask: [.titled, .resizable], backing: .buffered, defer: false)
            panelWindow.isReleasedWhenClosed = false
            panelWindow.contentViewController = controller
            controller.view.layoutSubtreeIfNeeded()
            self.model = model; self.controller = controller; self.panelWindow = panelWindow
            model.load()
            try settled()
        }

        func settled(file: String = #fileID, line: Int = #line) throws {
            try BindingAcceptance.wait(file: file, line: line) { self.model.loaded && !self.model.busy }
            controller.view.layoutSubtreeIfNeeded()
        }

        func item(_ title: String) throws -> WorkspaceMaterialItem {
            guard let item = model.items.first(where: { $0.title == title }) else {
                throw LabError.message("No 素材 titled \(title): \(model.items.map(\.title))")
            }
            return item
        }

        func card(_ item: WorkspaceMaterialItem) throws -> MaterialCardView {
            controller.view.layoutSubtreeIfNeeded()
            guard let card = controller.card(itemID: item.id) else { throw LabError.message("No card for \(item.title)") }
            return card
        }

        func press(_ identifier: String, on item: WorkspaceMaterialItem) throws {
            guard let entry = controller.menuItems(for: item).first(where: { $0.accessibilityIdentifier() == identifier }) as? LibraryMenuItem else {
                throw LabError.message("No menu item \(identifier)")
            }
            try BindingAcceptance.require(entry.isEnabled, "\(identifier) was disabled")
            entry.press()
        }

        // MARK: Journal

        /// The last change-set rowid; steps compare the originals after it.
        func mark() throws -> Int64 {
            guard case .integer(let value)? = try WorkspaceRemoteProseFixture.query(in: directory,
                sql: "SELECT COALESCE(MAX(rowid), 0) AS n FROM sync_change_set").first?["n"] else {
                throw LabError.message("Journal mark query returned no row")
            }
            return value
        }

        /// “action kind” of every mutation, one list per original after `since`.
        func originals(since: Int64) throws -> [[String]] {
            try WorkspaceRemoteProseFixture.query(in: directory,
                sql: "SELECT change_set_id FROM sync_change_set WHERE rowid > \(since) ORDER BY rowid").map { row in
                guard case .text(let id)? = row["change_set_id"] else { throw LabError.message("Journal row has no identity") }
                return try WorkspaceRemoteProseFixture.query(in: directory,
                    sql: "SELECT action || ' ' || target_kind AS m FROM sync_mutation WHERE change_set_id = ? ORDER BY mutation_index",
                    parameters: [.text(id)]).map { mutation in
                    guard case .text(let value)? = mutation["m"] else { throw LabError.message("Journal mutation is unreadable") }
                    return value
                }
            }
        }

        func expect(_ expected: [[String]], since: Int64, _ step: String) throws {
            let written = try originals(since: since)
            try BindingAcceptance.require(written == expected, "\(step) wrote \(written) instead of \(expected)")
        }

        // MARK: Synthetic files

        private func image(_ name: String, width: Int, height: Int, type: UTType) throws -> URL {
            let url = sources.appendingPathComponent(name)
            guard let context = CGContext(data: nil, width: width, height: height, bitsPerComponent: 8, bytesPerRow: 0,
                                          space: CGColorSpace(name: CGColorSpace.sRGB)!,
                                          bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) else {
                throw LabError.message("No bitmap context")
            }
            context.setFillColor(CGColor(srgbRed: 0.2, green: 0.4, blue: 0.7, alpha: 1))
            context.fill(CGRect(x: 0, y: 0, width: width, height: height))
            context.setFillColor(CGColor(srgbRed: 0.95, green: 0.8, blue: 0.3, alpha: 1))
            context.fill(CGRect(x: width / 4, y: height / 4, width: width / 2, height: height / 2))
            guard let cgImage = context.makeImage(),
                  let destination = CGImageDestinationCreateWithURL(url as CFURL, type.identifier as CFString, 1, nil) else {
                throw LabError.message("No image destination")
            }
            CGImageDestinationAddImage(destination, cgImage, nil)
            try BindingAcceptance.require(CGImageDestinationFinalize(destination), "Synthetic image was not written")
            return url
        }
        func png(_ name: String, width: Int, height: Int) throws -> URL { try image(name, width: width, height: height, type: .png) }
        func jpeg(_ name: String, width: Int, height: Int) throws -> URL { try image(name, width: width, height: height, type: .jpeg) }

        func pdf(_ name: String) throws -> URL {
            let url = sources.appendingPathComponent(name)
            var box = CGRect(x: 0, y: 0, width: 300, height: 420)
            guard let context = CGContext(url as CFURL, mediaBox: &box, nil) else { throw LabError.message("No PDF context") }
            context.beginPDFPage(nil)
            context.setFillColor(CGColor(srgbRed: 0.9, green: 0.9, blue: 0.85, alpha: 1))
            context.fill(box)
            context.setFillColor(CGColor(srgbRed: 0.3, green: 0.3, blue: 0.3, alpha: 1))
            context.fill(CGRect(x: 30, y: 300, width: 240, height: 20))
            context.endPDFPage()
            context.closePDF()
            return url
        }

        func text(_ name: String, _ content: String) throws -> URL {
            let url = sources.appendingPathComponent(name)
            try Data(content.utf8).write(to: url)
            return url
        }

        /// A Word document written by AppKit: a large bold heading and body
        /// paragraphs at the body size.
        func docx(_ name: String) throws -> URL {
            let url = sources.appendingPathComponent(name)
            let text = NSMutableAttributedString()
            text.append(NSAttributedString(string: "序章\n", attributes: [.font: NSFont.boldSystemFont(ofSize: 24)]))
            for line in ["钟声在雨夜里响起。\n", "她数到第十二下，推开了门。\n", "北塔的灯还亮着。"] {
                text.append(NSAttributedString(string: line, attributes: [.font: NSFont.systemFont(ofSize: 12)]))
            }
            let data = try text.data(from: NSRange(location: 0, length: text.length),
                                     documentAttributes: [.documentType: NSAttributedString.DocumentType.officeOpenXML])
            try data.write(to: url)
            return url
        }

        func pasteboard(_ urls: [URL]) -> NSPasteboard {
            let pasteboard = NSPasteboard(name: NSPasteboard.Name("drifting-library-\(UUID().uuidString)"))
            pasteboard.clearContents()
            pasteboard.writeObjects(urls as [NSURL])
            return pasteboard
        }

        func openElement(_ element: WorkspaceElement, pane: Int = 0) throws -> MacElementPageView {
            let view: NativeDocumentView = try BindingAcceptance.elementResult {
                host.open(project: project, element: element, in: pane, completion: $0)
            }
            try BindingAcceptance.elementSettled(host, view)
            guard let page = host.retainedElementPage(pane: pane, scope: ElementScope(projectID: project.id, elementID: element.id)) else {
                throw LabError.message("Element page was not retained")
            }
            return page
        }

        /// Closes every owner and the workspace, then opens the directory
        /// again with a new core and tab host.
        func coldReopen() throws {
            try BindingAcceptance.wait { self.host.canNavigate && !self.host.isBusy }
            let closed: Bool = try BindingAcceptance.elementResult { host.close(completion: $0) }
            try BindingAcceptance.require(closed, "Library workspace failed to close")
            window.close(); panelWindow?.close()
            let reopened = LabWorkspaceCore(directory: directory)
            workspace = reopened
            let projects: [WorkspaceProject] = try BindingAcceptance.elementResult { reopened.projects(completion: $0) }
            try BindingAcceptance.require(projects.map(\.id) == [project.id], "Cold reopen lost the project")
            (window, host) = BindingAcceptance.elementHost(reopened)
            model = nil; controller = nil; panelWindow = nil
        }

        func close() throws {
            try BindingAcceptance.wait { self.host.canNavigate && !self.host.isBusy }
            let closed: Bool = try BindingAcceptance.elementResult { host.close(completion: $0) }
            try BindingAcceptance.require(closed, "Library workspace failed to close")
            window.close(); panelWindow?.close()
        }

        func remove() { try? FileManager.default.removeItem(at: directory.deletingLastPathComponent()) }
    }

    private static func field(_ identifier: String, in view: NSView?) -> NSTextField? {
        guard let view else { return nil }
        if view.accessibilityIdentifier() == identifier, let field = view as? NSTextField { return field }
        for child in view.subviews { if let found = field(identifier, in: child) { return found } }
        return nil
    }

    private static func blocks(_ view: NativeDocumentView) -> [String] {
        view.binding.store.projection?.blocks.map { block in
            let text = ((view.binding.store.projection?.text ?? "") as NSString)
                .substring(with: NSRange(location: block.range.location, length: block.range.length))
            return block.kind == "heading" ? "h\(block.headingLevel) \(text)" : text
        } ?? []
    }

    static func libraryAcceptance() throws -> [String] {
        try libraryPanelImportsCards()
        try libraryPanelEditsAndDeletes()
        try libraryPortraits()
        try libraryImportExportAndReopen()
        return [
            "AppKit 素材库 imports a generated PNG and PDF through 导入文件… and a dropped JPEG, shows image and PDF cards whose downsampled thumbnails load, adds a link showing its host that opens in the browser and a note from the sheet, previews files through Quick Look and the space bar, and refuses a dropped text file and a javascript: link in Chinese without writing",
            "AppKit 素材库 renames through 重命名… and edits an image's notes and a note's body and notes through the sheet with one field.set per changed field, writes nothing for unchanged or empty titles, and deletes after confirmation, removing the card, the stored bytes and the item with one purge",
            "AppKit element page 肖像 shows the placeholder, sets a generated PNG through 设置肖像…, replaces it by a dropped JPEG releasing the previous bytes, follows in the second pane and the 设定库 row, refuses a PDF without writing and 移除肖像 clears it back to the placeholder",
            "AppKit 文件 › 导入… parses Markdown into a new chapter and plain text into a new element of the chosen category through the sheet with guessed and edited titles, a Word document with a larger heading into a 漂流, opening each page with its headings and paragraphs; 导出全书… writes UTF-8 Markdown and plain text; and the library, portrait and imported bodies survive a cold reopen",
        ]
    }

    // MARK: (a) Import, cards, links, notes and Quick Look

    private static func libraryPanelImportsCards() throws {
        let harness = try LibraryHarness()
        defer { harness.remove() }
        try harness.openPanel()
        try require(harness.model.items.isEmpty && harness.model.status.contains("还没有素材"), "A new library was not empty")
        let png = try harness.png("北塔.png", width: 1200, height: 800)
        let pdf = try harness.pdf("考据.pdf")
        var mark = try harness.mark()
        harness.controller.chooseFiles = { done in done([png, pdf]) }
        harness.controller.importButton.performClick(nil)
        try harness.settled()
        try require(harness.model.items.map(\.title) == ["北塔", "考据"], "Imports did not list in order: \(harness.model.items.map(\.title))")
        let image = try harness.item("北塔"), document = try harness.item("考据")
        try require(image.kind == "image" && image.asset?.mime == "image/png" && image.asset?.width == 1200 && image.asset?.height == 800,
            "The PNG was not described by ImageIO: \(String(describing: image.asset))")
        try require(document.kind == "pdf" && document.asset?.mime == "application/pdf" && document.asset?.width == nil, "The PDF kind differs")
        for (item, source, suffix) in [(image, png, "/source.png"), (document, pdf, "/source.pdf")] {
            guard let path = item.assetPath else { throw LabError.message("\(item.title) has no stored path") }
            try require(path.hasSuffix(suffix) && path.contains("/apple-native-lab/assets/\(harness.project.id)/"),
                "Stored path is outside the store: \(path)")
            try require(FileManager.default.contentsEqual(atPath: path, andPath: source.path), "Stored bytes differ from \(item.title)")
        }
        try harness.expect([["entity.create library-item"], ["entity.create library-item"]], since: mark, "Two imports")
        let imageCard = try harness.card(image), pdfCard = try harness.card(document)
        try require(imageCard.detailLabel.stringValue.hasPrefix("图片 · 1200 × 800 · ") && pdfCard.detailLabel.stringValue.hasPrefix("PDF · "),
            "Card details differ: \(imageCard.detailLabel.stringValue) / \(pdfCard.detailLabel.stringValue)")
        try wait { imageCard.thumbnailLoaded && pdfCard.thumbnailLoaded }
        let thumbnail = imageCard.well.imageView.image?.size ?? .zero
        try require(max(thumbnail.width, thumbnail.height) <= 128 && thumbnail.width > thumbnail.height,
            "The image thumbnail was not downsampled: \(thumbnail)")
        try require((pdfCard.well.imageView.image?.size.height ?? 0) > (pdfCard.well.imageView.image?.size.width ?? 0),
            "The PDF thumbnail is not its portrait first page")

        // A drop imports the images it carries; a text file is refused by name.
        let jpeg = try harness.jpeg("雨夜.jpg", width: 64, height: 40)
        let note = try harness.text("说明.txt", "不是图片")
        mark = try harness.mark()
        try require(harness.controller.importDropped(from: harness.pasteboard([jpeg, note])), "The drop was not accepted")
        try harness.settled()
        let photo = try harness.item("雨夜")
        try require(photo.asset?.mime == "image/jpeg" && photo.assetPath?.hasSuffix("/source.jpg") == true
            && FileManager.default.fileExists(atPath: photo.assetPath ?? ""), "The JPEG was not stored under its MIME extension")
        try require(harness.model.status.contains("说明.txt") && harness.model.status.contains("只能导入图片或 PDF"),
            "The text file was not refused in Chinese: \(harness.model.status)")
        try harness.expect([["entity.create library-item"]], since: mark, "The drop")

        // 添加链接…: an empty title becomes the host; javascript: is refused.
        harness.answer = { alert in
            field("new-material-link-url", in: alert.accessoryView)?.stringValue = "https://example.invalid/north-tower"
            return .alertFirstButtonReturn
        }
        mark = try harness.mark()
        harness.controller.linkButton.performClick(nil)
        try harness.settled()
        let link = try harness.item("example.invalid")
        try require(link.kind == "url" && link.externalUrl == "https://example.invalid/north-tower", "The link was not stored")
        try require(try harness.card(link).detailLabel.stringValue == "example.invalid/north-tower",
            "The link card titled by its host does not show its address")
        // A titled link shows its host; an address without a scheme is https.
        harness.answer = { alert in
            field("new-material-link-title", in: alert.accessoryView)?.stringValue = "北塔资料"
            field("new-material-link-url", in: alert.accessoryView)?.stringValue = "example.invalid/archive"
            return .alertFirstButtonReturn
        }
        harness.controller.linkButton.performClick(nil)
        try harness.settled()
        let titled = try harness.item("北塔资料")
        try require(titled.externalUrl == "https://example.invalid/archive" && (try harness.card(titled).detailLabel.stringValue) == "example.invalid",
            "The titled link card does not show its host")
        try harness.expect([["entity.create library-item"], ["entity.create library-item"]], since: mark, "The links")
        harness.answer = { alert in
            field("new-material-link-title", in: alert.accessoryView)?.stringValue = "脚本"
            field("new-material-link-url", in: alert.accessoryView)?.stringValue = "javascript:alert(1)"
            return .alertFirstButtonReturn
        }
        mark = try harness.mark()
        harness.controller.linkButton.performClick(nil)
        try harness.settled()
        try require(harness.model.status.contains("链接必须以 http:// 或 https:// 开头") && harness.model.items.count == 5,
            "A javascript: link was not refused: \(harness.model.status)")
        try harness.expect([], since: mark, "The refused link")
        harness.controller.preview(link)
        try require(harness.opened == [URL(string: "https://example.invalid/north-tower")!], "The link did not open in the browser")

        // 新建笔记 through the sheet.
        mark = try harness.mark()
        harness.controller.noteButton.performClick(nil)
        guard let sheet = harness.controller.editSheet, sheet.item == nil, sheet.hasBody else { throw LabError.message("新建笔记 opened no sheet") }
        sheet.titleField.stringValue = "雨夜灵感"
        sheet.bodyView.string = "钟声\n雨夜"
        sheet.saveButton.performClick(nil)
        try wait { harness.controller.editSheet == nil && !harness.model.busy }
        let text = try harness.item("雨夜灵感")
        try require(text.kind == "text" && text.text == "钟声\n雨夜" && text.notes.isEmpty, "The note body differs: \(text.text)")
        try require(try harness.card(text).detailLabel.stringValue == "钟声\n雨夜", "The note card does not show its first lines")
        try harness.expect([["entity.create library-item"]], since: mark, "The note")

        // Quick Look shows the stored file, from the menu and the space bar.
        try harness.press("preview-material", on: image)
        try require(harness.quickLooked.last == [URL(fileURLWithPath: image.assetPath!)], "快速查看 did not preview the stored image")
        try require(harness.controller.numberOfPreviewItems(in: nil) == 1
            && (harness.controller.previewPanel(nil, previewItemAt: 0) as? NSURL)?.path == image.assetPath,
            "The Quick Look data source differs")
        harness.controller.select(itemID: document.id)
        let space = NSEvent.keyEvent(with: .keyDown, location: .zero, modifierFlags: [], timestamp: 0,
                                     windowNumber: harness.panelWindow.windowNumber, context: nil, characters: " ",
                                     charactersIgnoringModifiers: " ", isARepeat: false, keyCode: 49)!
        harness.controller.table.keyDown(with: space)
        try require(harness.quickLooked.last == [URL(fileURLWithPath: document.assetPath!)], "Space did not preview the selected PDF")
        try require(harness.opened.count == 1, "Quick Look opened a browser")
        try harness.close()
    }

    // MARK: (b) Rename, notes, body and delete

    private static func libraryPanelEditsAndDeletes() throws {
        let harness = try LibraryHarness()
        defer { harness.remove() }
        try harness.openPanel()
        let png = try harness.png("封面.png", width: 80, height: 120)
        harness.controller.chooseFiles = { done in done([png]) }
        harness.controller.importButton.performClick(nil)
        try harness.settled()
        harness.controller.noteButton.performClick(nil)
        harness.controller.editSheet?.titleField.stringValue = "灵感"
        harness.controller.editSheet?.bodyView.string = "钟声"
        harness.controller.editSheet?.saveButton.performClick(nil)
        try wait { harness.controller.editSheet == nil && !harness.model.busy }
        var image = try harness.item("封面")

        // 重命名…: one field.set; the same or an empty title writes nothing.
        var mark = try harness.mark()
        harness.answer = { alert in
            field("rename-material-title", in: alert.accessoryView)?.stringValue = "  北塔远景 "
            return .alertFirstButtonReturn
        }
        try harness.press("rename-material", on: image)
        try harness.settled()
        image = try harness.item("北塔远景")
        try require(try harness.card(image).titleLabel.stringValue == "北塔远景", "The card title did not follow the rename")
        try harness.expect([["field.set library-item"]], since: mark, "The rename")
        mark = try harness.mark()
        try harness.press("rename-material", on: image)
        try harness.settled()
        harness.answer = { alert in
            field("rename-material-title", in: alert.accessoryView)?.stringValue = "   "
            return .alertFirstButtonReturn
        }
        try harness.press("rename-material", on: image)
        try require(harness.model.status == "标题不能为空。", "An empty title was not refused: \(harness.model.status)")
        harness.answer = nil
        try harness.press("rename-material", on: image)
        try harness.expect([], since: mark, "Unchanged, empty and cancelled renames")

        // 编辑备注… on an image: the sheet has no body.
        mark = try harness.mark()
        try harness.press("edit-material-notes", on: image)
        guard let notesSheet = harness.controller.editSheet, !notesSheet.hasBody else { throw LabError.message("编辑备注… opened no notes sheet") }
        notesSheet.notesView.string = "封面参考"
        notesSheet.saveButton.performClick(nil)
        try wait { harness.controller.editSheet == nil && !harness.model.busy }
        image = try harness.item("北塔远景")
        try require(image.notes == "封面参考" && (try harness.card(image).notesLabel.stringValue) == "备注：封面参考", "Notes were not shown")
        try harness.expect([["field.set library-item"]], since: mark, "The notes")

        // 编辑笔记…: body and notes in one original with two field.sets.
        var note = try harness.item("灵感")
        mark = try harness.mark()
        try harness.press("edit-material-note", on: note)
        guard let noteSheet = harness.controller.editSheet, noteSheet.hasBody, noteSheet.bodyView.string == "钟声" else {
            throw LabError.message("编辑笔记… did not show the body")
        }
        noteSheet.bodyView.string = "钟声\n雨夜\n北塔"
        noteSheet.notesView.string = "第二章用"
        noteSheet.saveButton.performClick(nil)
        try wait { harness.controller.editSheet == nil && !harness.model.busy }
        note = try harness.item("灵感")
        try require(note.text == "钟声\n雨夜\n北塔" && note.notes == "第二章用", "The note was not saved: \(note.text) / \(note.notes)")
        try require(try harness.card(note).detailLabel.stringValue == "钟声\n雨夜", "The note card shows more than two lines")
        try harness.expect([["field.set library-item", "field.set library-item"]], since: mark, "The note body and notes")
        mark = try harness.mark()
        try harness.press("edit-material-note", on: note)
        harness.controller.editSheet?.saveButton.performClick(nil)
        try wait { harness.controller.editSheet == nil && !harness.model.busy }
        try harness.expect([], since: mark, "An unchanged sheet")
        // An emptied title is refused in the sheet, which keeps the typed body.
        try harness.press("edit-material-note", on: note)
        harness.controller.editSheet?.titleField.stringValue = " "
        harness.controller.editSheet?.bodyView.string = "新的正文"
        harness.controller.editSheet?.saveButton.performClick(nil)
        try require(harness.controller.editSheet?.errorMessage == "标题不能为空。" && harness.controller.editSheet?.bodyView.string == "新的正文",
            "The sheet did not keep the typed text on refusal")
        harness.controller.editSheet?.cancelButton.performClick(nil)
        try require(harness.controller.editSheet == nil, "取消 did not close the sheet")
        try harness.expect([], since: mark, "The refused sheet")

        // 删除…: cancelling keeps everything; confirming removes rows and bytes.
        let stored = try require(image.assetPath)
        harness.answer = { _ in .alertSecondButtonReturn }
        try harness.press("delete-material", on: image)
        try harness.settled()
        try require(harness.model.items.count == 2 && FileManager.default.fileExists(atPath: stored), "A cancelled delete removed the item")
        try harness.expect([], since: mark, "A cancelled delete")
        var confirmation: String?
        harness.answer = { alert in confirmation = alert.messageText; return .alertFirstButtonReturn }
        try harness.press("delete-material", on: image)
        try harness.settled()
        try require(confirmation == "删除素材“北塔远景”？", "The delete confirmation names another item: \(confirmation ?? "none")")
        try require(harness.model.items.map(\.title) == ["灵感"] && harness.controller.card(itemID: image.id) == nil,
            "The deleted card remained")
        try require(!FileManager.default.fileExists(atPath: stored), "The stored bytes survived the delete")
        try harness.expect([["entity.purge library-item"]], since: mark, "The delete")
        try harness.close()
    }

    // MARK: (c) Portraits

    private static func libraryPortraits() throws {
        let harness = try LibraryHarness()
        defer { harness.remove() }
        let workspace = harness.workspace, projectID = harness.project.id
        let category: WorkspaceElementReply<WorkspaceElementCategory> = try elementResult {
            workspace.createElementCategory(projectID: projectID, name: "人物", completion: $0)
        }
        let created: WorkspaceElementReply<WorkspaceElement> = try elementResult {
            workspace.createElement(projectID: projectID, categoryID: category.result!.id, name: "米拉", completion: $0)
        }
        let element = created.result!
        let page = try harness.openElement(element)
        try wait { page.portraitLoaded }
        try require(page.portraitView.shownPath == nil && !page.portraitView.hasImage && page.portraitView.removeButton.isHidden
            && page.portraitView.setButton.title == "设置肖像…", "A new element did not show the placeholder")

        // 设置肖像… through the picker.
        let png = try harness.png("米拉.png", width: 90, height: 120)
        page.portraitView.chooseFile = { done in done(png) }
        var mark = try harness.mark()
        page.portraitView.setButton.performClick(nil)
        try wait { !page.portraitView.isBusy && page.portraitView.hasImage }
        let first = try require(page.portraitView.shownPath)
        try require(FileManager.default.contentsEqual(atPath: first, andPath: png.path) && first.hasSuffix("/source.png"),
            "The portrait bytes were not stored")
        try require(page.portraitView.setButton.title == "更换肖像…" && !page.portraitView.removeButton.isHidden, "The portrait actions did not follow")
        try harness.expect([["field.set element"]], since: mark, "Setting the portrait")

        // The 设定库 row shows it small.
        let libraryModel = ElementLibraryModel(workspace: workspace, projectID: projectID)
        let library = MacElementLibraryViewController(model: libraryModel)
        let host = harness.host
        library.portraitPath = { id in host.materialLibrary(projectID: projectID)?.portrait(elementID: id)?.assetPath }
        let libraryWindow = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 360, height: 600), styleMask: [.titled], backing: .buffered, defer: false)
        libraryWindow.isReleasedWhenClosed = false
        libraryWindow.contentViewController = library
        libraryModel.load()
        try wait { libraryModel.loaded && !libraryModel.busy }
        library.view.layoutSubtreeIfNeeded()
        func table(in view: NSView) -> NSTableView? {
            if let table = view as? NSTableView { return table }
            return view.subviews.lazy.compactMap(table).first
        }
        func rowWell() -> MaterialPreviewWell? {
            guard let row = library.rows.firstIndex(where: { $0.element?.id == element.id }),
                  let table = table(in: library.view),
                  let view = table.view(atColumn: 0, row: row, makeIfNecessary: true) else { return nil }
            func find(_ view: NSView) -> MaterialPreviewWell? {
                if let well = view as? MaterialPreviewWell, well.accessibilityIdentifier() == "element-row-portrait-\(element.id)" { return well }
                return view.subviews.lazy.compactMap(find).first
            }
            return find(view)
        }
        try wait { rowWell()?.loadedPath == first }

        // A dropped JPEG replaces it; the previous bytes are released.
        let jpeg = try harness.jpeg("米拉-新.jpg", width: 60, height: 60)
        mark = try harness.mark()
        try require(page.portraitView.acceptDrop(from: harness.pasteboard([jpeg])), "The portrait drop was not accepted")
        try wait { !page.portraitView.isBusy && page.portraitView.hasImage && page.portraitView.shownPath != first }
        let second = try require(page.portraitView.shownPath)
        try require(second.hasSuffix("/source.jpg") && FileManager.default.fileExists(atPath: second)
            && !FileManager.default.fileExists(atPath: first), "Replacing did not release the previous portrait")
        try harness.expect([["field.set element"]], since: mark, "Replacing the portrait")

        // The same element in the second pane shows the same portrait.
        let split: NativeDocumentView = try elementResult { host.split(completion: $0) }
        try elementSettled(host, split)
        guard let other = host.retainedElementPage(pane: 1, scope: ElementScope(projectID: projectID, elementID: element.id)) else {
            throw LabError.message("The second pane has no element page")
        }
        try wait { other.portraitView.shownPath == second && other.portraitView.hasImage }
        library.reload()
        try wait { rowWell()?.loadedPath == second }

        // A PDF is refused before Rust; nothing is written.
        let pdf = try harness.pdf("不是肖像.pdf")
        mark = try harness.mark()
        try require(page.portraitView.acceptDrop(from: harness.pasteboard([pdf])), "The PDF drop was ignored")
        try wait { !page.portraitView.isBusy }
        try require(page.errorMessage?.contains("肖像只能使用图片") == true && page.portraitView.shownPath == second,
            "A PDF portrait was not refused: \(page.errorMessage ?? "none")")
        try harness.expect([], since: mark, "The refused portrait")

        // 移除肖像 from the second pane clears both pages.
        mark = try harness.mark()
        other.portraitView.removeButton.performClick(nil)
        try wait { !other.portraitView.isBusy && other.portraitView.shownPath == nil && page.portraitView.shownPath == nil }
        try require(!FileManager.default.fileExists(atPath: second) && page.portraitView.removeButton.isHidden
            && page.portraitView.setButton.title == "设置肖像…", "Removing did not restore the placeholder")
        try harness.expect([["field.set element"]], since: mark, "Removing the portrait")
        library.reload()
        try require(rowWell() == nil, "The 设定库 row kept a removed portrait")
        libraryWindow.close()
        try harness.close()
    }

    // MARK: (d) Import, export and cold reopen

    private static func libraryImportExportAndReopen() throws {
        let harness = try LibraryHarness()
        defer { harness.remove() }
        let workspace = harness.workspace, projectID = harness.project.id
        let category: WorkspaceElementReply<WorkspaceElementCategory> = try elementResult {
            workspace.createElementCategory(projectID: projectID, name: "人物", completion: $0)
        }
        let categoryID = category.result!.id
        let transfer = MacBookTransfer(workspace: workspace, host: harness.host)
        var statuses: [String] = []
        transfer.onStatus = { statuses.append($0) }
        var imported: [WorkspaceImportedEntity] = []
        transfer.onImported = { _, entity in imported.append(entity) }
        let host = harness.host

        // Markdown into a chapter.
        let markdown = try harness.text("北塔.md", """
            ---
            tags: 合成
            ---
            # 北塔

            她推开**北塔**的门，
            钟声响起。

            ## 钟楼

            - 铜钟
            - [旧图](https://example.invalid/map)

            > 引文一行

            #### 更深的标题

            结尾有 `代码` 与 *斜体*。
            """)
        var chosen = markdown
        transfer.chooseImportFile = { _, done in done(chosen) }
        transfer.beginImport(project: harness.project, window: nil)
        guard let markdownSheet = transfer.importSheet else { throw LabError.message("导入… showed no sheet: \(statuses)") }
        try require(markdownSheet.titleField.stringValue == "北塔" && markdownSheet.selectedKind == "chapter",
            "The Markdown title was not guessed from the first heading")
        try require(markdownSheet.summary.stringValue == "Markdown · 8 段，其中 3 个标题"
            && markdownSheet.preview.stringValue.hasPrefix("# 北塔\n她推开北塔的门，钟声响起。\n## 钟楼\n- 铜钟\n- 旧图"),
            "The import preview differs: \(markdownSheet.summary.stringValue) / \(markdownSheet.preview.stringValue)")
        var mark = try harness.mark()
        markdownSheet.importButton.performClick(nil)
        try wait { transfer.importSheet == nil && host.activeChapter?.title == "北塔" }
        guard let chapterView = host.activeView else { throw LabError.message("The imported chapter did not open") }
        try elementSettled(host, chapterView)
        let chapterBlocks = ["h1 北塔", "她推开北塔的门，钟声响起。", "h2 钟楼", "- 铜钟", "- 旧图", "引文一行", "h3 更深的标题", "结尾有 代码 与 斜体。"]
        try require(blocks(chapterView) == chapterBlocks, "The chapter body differs: \(blocks(chapterView))")
        let chapterOriginals = try harness.originals(since: mark)
        try require(chapterOriginals.first?.contains("entity.create node") == true
            && chapterOriginals.dropFirst().allSatisfy({ $0.allSatisfy { $0.hasPrefix("yjs.update") } }),
            "The chapter import wrote \(chapterOriginals)")
        try require(imported.count == 1, "onImported was not told about the chapter")

        // Plain text into an element of the chosen category, with an edited title.
        chosen = try harness.text("米拉.txt", "米拉\n\n她在北塔长大。\n常去钟楼。\n\nMira likes\nrainy nights.\n")
        transfer.beginImport(project: harness.project, window: nil)
        guard let textSheet = transfer.importSheet else { throw LabError.message("导入… showed no text sheet") }
        try require(textSheet.titleField.stringValue == "米拉" && textSheet.summary.stringValue == "纯文本 · 3 段",
            "The text title or summary differs: \(textSheet.summary.stringValue)")
        try wait { textSheet.categoryPopup.itemArray.contains { $0.representedObject as? String == categoryID } }
        textSheet.select(kind: "element")
        try require(!textSheet.categoryPopup.isHidden && textSheet.categoryPopup.isEnabled && textSheet.importButton.isEnabled,
            "The category popup did not appear for 设定")
        textSheet.select(categoryID: categoryID)
        textSheet.titleField.stringValue = "米拉档案"
        mark = try harness.mark()
        textSheet.importButton.performClick(nil)
        try wait { transfer.importSheet == nil && host.activeElement?.name == "米拉档案" }
        guard let elementView = host.activeView, let element = host.activeElement else { throw LabError.message("The element did not open") }
        try elementSettled(host, elementView)
        try require(element.categoryId == categoryID, "The element was not created in the chosen category")
        try require(blocks(elementView) == ["米拉", "她在北塔长大。常去钟楼。", "Mira likes rainy nights."],
            "The element body differs: \(blocks(elementView))")
        try require(try harness.originals(since: mark).first?.contains("entity.create element") == true, "The element import wrote no element")

        // An empty file is refused before any sheet.
        chosen = try harness.text("空白.md", "\n\n   \n")
        mark = try harness.mark()
        transfer.beginImport(project: harness.project, window: nil)
        try require(transfer.importSheet == nil && statuses.last == "“空白.md”中没有可导入的文字。", "An empty file was not refused: \(statuses)")
        try harness.expect([], since: mark, "The empty import")

        // A Word document with a larger heading into a 漂流.
        chosen = try harness.docx("序章草稿.docx")
        transfer.beginImport(project: harness.project, window: nil)
        guard let docxSheet = transfer.importSheet else { throw LabError.message("导入… showed no Word sheet: \(statuses)") }
        try require(docxSheet.titleField.stringValue == "序章草稿" && docxSheet.summary.stringValue == "Word 文档 · 4 段，其中 1 个标题",
            "The Word document was parsed differently: \(docxSheet.summary.stringValue) / \(docxSheet.preview.stringValue)")
        docxSheet.select(kind: "drift")
        try require(docxSheet.categoryPopup.isHidden, "The category popup stayed for 漂流")
        docxSheet.importButton.performClick(nil)
        do { try wait { transfer.importSheet == nil && host.activeDrift?.title == "序章草稿" } } catch {
            throw LabError.message("The drift import did not open: \(docxSheet.errorMessage ?? "no sheet error") / \(statuses) / \(String(describing: host.activeDrift))")
        }
        guard let driftView = host.activeView else { throw LabError.message("The drift did not open") }
        try elementSettled(host, driftView)
        try require(blocks(driftView) == ["h1 序章", "钟声在雨夜里响起。", "她数到第十二下，推开了门。", "北塔的灯还亮着。"],
            "The drift body differs: \(blocks(driftView))")

        // 导出全书… as Markdown and plain text.
        let exports = harness.sources.appendingPathComponent("exports", isDirectory: true)
        try FileManager.default.createDirectory(at: exports, withIntermediateDirectories: true)
        var destination: (URL, BookExportFormat)?
        var suggestedNames: [String] = []
        transfer.chooseExportDestination = { _, name, done in suggestedNames.append(name); done(destination) }
        destination = (exports.appendingPathComponent("全书.md"), .markdown)
        mark = try harness.mark()
        let markdownURL: URL = try elementResult { transfer.beginExport(project: harness.project, window: nil, completion: $0) }
        let exported = try String(contentsOf: markdownURL, encoding: .utf8)
        try require(exported.hasPrefix("# 素材库合成项目\n\n## 雨夜\n\n## 北塔\n\n### 北塔\n\n她推开北塔的门，钟声响起。\n\n#### 钟楼\n\n"),
            "The Markdown export differs:\n\(exported)")
        try require(exported.contains("引文一行") && exported.contains("\n\n##### 更深的标题\n\n结尾有 代码 与 斜体。\n")
            && !exported.contains("序章") && !exported.contains("米拉"), "The Markdown export has other content:\n\(exported)")
        destination = (exports.appendingPathComponent("全书.txt"), .text)
        let textURL: URL = try elementResult { transfer.beginExport(project: harness.project, window: nil, completion: $0) }
        let plain = try String(contentsOf: textURL, encoding: .utf8)
        try require(plain.hasPrefix("素材库合成项目\n\n雨夜\n\n北塔\n\n北塔\n她推开北塔的门，钟声响起。\n钟楼\n") && !plain.contains("#"),
            "The text export differs:\n\(plain)")
        try harness.expect([], since: mark, "Exporting")
        try require(suggestedNames == ["素材库合成项目", "素材库合成项目"], "The export was not named after the book: \(suggestedNames)")
        try require(statuses.last == "全书已导出为纯文本：全书.txt", "The export status differs: \(statuses.last ?? "")")

        // A library item and a portrait for the cold reopen.
        try harness.openPanel()
        let png = try harness.png("档案照.png", width: 40, height: 40)
        harness.controller.chooseFiles = { done in done([png]) }
        harness.controller.importButton.performClick(nil)
        try harness.settled()
        harness.controller.noteButton.performClick(nil)
        harness.controller.editSheet?.titleField.stringValue = "旁注"
        harness.controller.editSheet?.bodyView.string = "钟楼\n十二下"
        harness.controller.editSheet?.notesView.string = "备查"
        harness.controller.editSheet?.saveButton.performClick(nil)
        try wait { harness.controller.editSheet == nil && !harness.model.busy }
        guard let page = host.retainedElementPage(pane: 0, scope: ElementScope(projectID: projectID, elementID: element.id)) else {
            throw LabError.message("The imported element page was not retained")
        }
        page.portraitView.chooseFile = { done in done(png) }
        page.portraitView.setButton.performClick(nil)
        try wait { !page.portraitView.isBusy && page.portraitView.hasImage }
        let portrait = try require(page.portraitView.shownPath)
        let before = harness.model.items

        // Cold reopen: a new core, tab host and panel over the same directory.
        try harness.coldReopen()
        try harness.openPanel()
        try require(harness.model.items == before, "The library changed across a cold reopen")
        try require(harness.model.items.compactMap(\.assetPath).allSatisfy { FileManager.default.fileExists(atPath: $0) }, "Stored bytes were lost")
        let note = try harness.item("旁注")
        try require(note.text == "钟楼\n十二下" && note.notes == "备查", "The note did not survive")
        let reopenedPage = try harness.openElement(element)
        try wait { reopenedPage.portraitView.shownPath == portrait && reopenedPage.portraitView.hasImage }
        try require(blocks(reopenedPage.documentView) == ["米拉", "她在北塔长大。常去钟楼。", "Mira likes rainy nights."],
            "The element body did not survive")
        guard case .chapter(let chapter)? = imported.first else { throw LabError.message("No imported chapter") }
        let reopenedChapter: NativeDocumentView = try elementResult { harness.host.open(project: harness.project, chapter: chapter, completion: $0) }
        try elementSettled(harness.host, reopenedChapter)
        try require(blocks(reopenedChapter) == chapterBlocks, "The chapter body did not survive: \(blocks(reopenedChapter))")
        try harness.close()
    }

    private static func require<T>(_ value: T?, file: String = #fileID, line: Int = #line) throws -> T {
        guard let value else { throw LabError.message("Missing value at \(file):\(line)") }
        return value
    }
}
