import AppKit
import CoreText

/// 设置 through the real settings window controllers, `LabSettingsStore`,
/// the tab host and body editors, as AppDelegate wires them. Controls are
/// driven programmatically; every font file is generated by the test.
extension BindingAcceptance {
    static func settingsAcceptance() throws -> [String] {
        defer { LabSettingsStore.restoreUnconfigured() }
        try settingsApplyToOpenEditors()
        try settingsImportedFont()
        try settingsPersistAcrossRelaunch()
        try settingsFontFallback()
        return [
            "AppKit 设置 font source, size, line height, paragraph indent, manuscript language, theme, accent and spelling restyle every open editor in both panes and a hidden tab in place, keep text, selection and history, match the full style reference after typing, and 还原推荐样式 restores the defaults",
            "AppKit 设置 imports a generated TrueType font into the lab data directory, registers it for this process only and sets prose in it with CJK falling back to the serif, replaces and removes it with its copy, and refuses a damaged file and a text file in Chinese without changing anything",
            "AppKit 设置 persist in settings.json in the lab data directory and survive a cold relaunch of the store, window and tab host with the imported font registered again and every control and open editor restored",
            "AppKit 设置 fall back to the system serif with a Chinese message when a chosen system family is uninstalled or the imported copy is missing or damaged, and refuse an unknown family without changing the font",
        ]
    }

    // MARK: Harness

    private final class SettingsHarness {
        let root: URL
        let directory: URL
        private(set) var workspace: LabWorkspaceCore
        let project: WorkspaceProject
        let chapter: WorkspaceChapter
        let other: WorkspaceChapter
        private(set) var window: NSWindow
        private(set) var host: MacChapterWorkspace
        private(set) var store: LabSettingsStore
        private(set) var settings: MacSettingsWindowController
        var sources: URL { root.appendingPathComponent("sources", isDirectory: true) }
        var editor: MacEditorSettingsViewController { settings.editorPane }

        init() throws {
            root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
            directory = root.appendingPathComponent("apple-native-lab")
            try FileManager.default.createDirectory(at: root.appendingPathComponent("sources"), withIntermediateDirectories: true)
            let workspace = LabWorkspaceCore(directory: directory)
            self.workspace = workspace
            let listed: [WorkspaceProject] = try BindingAcceptance.elementResult { workspace.projects(completion: $0) }
            try BindingAcceptance.require(listed.isEmpty, "Settings fixture was not isolated")
            project = try BindingAcceptance.elementResult { workspace.createProject(name: "设置合成项目", completion: $0) }
            let projectID = project.id
            chapter = try BindingAcceptance.elementResult { workspace.createChapter(projectID: projectID, title: "雨夜", completion: $0) }
            other = try BindingAcceptance.elementResult { workspace.createChapter(projectID: projectID, title: "钟楼", completion: $0) }
            (window, host) = BindingAcceptance.elementHost(workspace)
            // As at launch: the store reads the lab data directory and applies.
            store = LabSettingsStore(directory: workspace.dataDirectory)
            store.apply()
            settings = Self.controller(store)
        }

        private static func controller(_ store: LabSettingsStore) -> MacSettingsWindowController {
            let controller = MacSettingsWindowController(store: store)
            _ = controller.appearancePane.view; _ = controller.editorPane.view; _ = controller.languagePane.view
            return controller
        }

        func open(_ chapter: WorkspaceChapter, pane: Int? = nil) throws -> NativeDocumentView {
            let view: NativeDocumentView = try BindingAcceptance.elementResult {
                host.open(project: project, chapter: chapter, in: pane, completion: $0)
            }
            try BindingAcceptance.elementSettled(host, view)
            return view
        }

        /// Types text at a UTF-16 location and waits for it to settle.
        func type(_ text: String, at location: Int, in view: NativeDocumentView) throws {
            view.textView.insertText(text, replacementRange: NSRange(location: location, length: 0))
            try BindingAcceptance.wait { !view.binding.hasPendingWork || view.binding.hasFailedDraft }
            try BindingAcceptance.require(!view.binding.hasFailedDraft, "Typing \(text) failed")
        }

        /// A fresh process: editors lose every setting and imported fonts are
        /// no longer registered; then a new workspace, tab host, store and
        /// settings window over the same directories, applied as at launch.
        func relaunch() throws {
            try BindingAcceptance.wait { self.host.canNavigate && !self.host.isBusy }
            let closed: Bool = try BindingAcceptance.elementResult { host.close(completion: $0) }
            try BindingAcceptance.require(closed, "Settings workspace failed to close")
            window.close(); settings.close()
            LabSettingsStore.restoreUnconfigured()
            if let fonts = try? FileManager.default.contentsOfDirectory(at: store.fontsDirectory, includingPropertiesForKeys: nil) {
                fonts.forEach(LabSettingsStore.unregister)
            }
            let reopened = LabWorkspaceCore(directory: directory)
            workspace = reopened
            let projects: [WorkspaceProject] = try BindingAcceptance.elementResult { reopened.projects(completion: $0) }
            try BindingAcceptance.require(projects.map(\.id) == [project.id], "Relaunch lost the project")
            (window, host) = BindingAcceptance.elementHost(reopened)
            store = LabSettingsStore(directory: reopened.dataDirectory)
            store.apply()
            settings = Self.controller(store)
        }

        func close() throws {
            try BindingAcceptance.wait { self.host.canNavigate && !self.host.isBusy }
            let closed: Bool = try BindingAcceptance.elementResult { host.close(completion: $0) }
            try BindingAcceptance.require(closed, "Settings workspace failed to close")
            window.close(); settings.close()
            if let fonts = try? FileManager.default.contentsOfDirectory(at: store.fontsDirectory, includingPropertiesForKeys: nil) {
                fonts.forEach(LabSettingsStore.unregister)
            }
            LabSettingsStore.restoreUnconfigured()
        }

        func remove() { try? FileManager.default.removeItem(at: root) }

        /// A generated TrueType font file named after its family.
        func font(_ family: String, file: String) throws -> URL {
            let url = sources.appendingPathComponent(file)
            try BindingAcceptance.syntheticFont(family: family).write(to: url)
            return url
        }
    }

    // MARK: Controls

    private static func choose(_ popup: NSPopUpButton, _ index: Int) {
        popup.selectItem(at: index); popup.sendAction(popup.action, to: popup.target)
    }
    private static func choose(_ control: NSSegmentedControl, _ index: Int) {
        control.selectedSegment = index; control.sendAction(control.action, to: control.target)
    }
    private static func slide(_ slider: NSSlider, _ value: Double) {
        slider.doubleValue = value; slider.sendAction(slider.action, to: slider.target)
    }
    private static func click(_ control: NSControl) { control.sendAction(control.action, to: control.target) }
    private static func fontSource(_ source: LabSettings.FontSource) -> Int { LabSettings.FontSource.allCases.firstIndex(of: source)! }

    // MARK: Inspection

    private static func attributes(_ view: NativeDocumentView, at index: Int) -> [NSAttributedString.Key: Any] {
        view.textView.textStorage!.attributes(at: index, effectiveRange: nil)
    }
    private static func storedFont(_ view: NativeDocumentView, at index: Int) -> NSFont {
        attributes(view, at: index)[.font] as! NSFont
    }
    private static func paragraph(_ view: NativeDocumentView, at index: Int) -> NSParagraphStyle {
        attributes(view, at: index)[.paragraphStyle] as! NSParagraphStyle
    }
    /// The face CoreText draws one character with, after fallback.
    private static func drawnFont(_ view: NativeDocumentView, at index: Int) -> String {
        let text = view.textView.textStorage!.attributedSubstring(from: NSRange(location: index, length: 1))
        guard let run = (CTLineGetGlyphRuns(CTLineCreateWithAttributedString(text)) as? [CTRun])?.first,
              let font = (CTRunGetAttributes(run) as NSDictionary)[kCTFontAttributeName] else { return "" }
        return CTFontCopyPostScriptName(font as! CTFont) as String
    }
    private static func dark(_ appearance: NSAppearance) -> Bool { appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua }

    private static func location(of text: String, in view: NativeDocumentView) throws -> Int {
        let range = (view.textView.string as NSString).range(of: text)
        guard range.location != NSNotFound else { throw LabError.message("“\(text)” is not in the editor") }
        return range.location
    }

    /// The body every case writes: a heading and two paragraphs mixing Latin and CJK.
    private static func writeBody(_ harness: SettingsHarness, _ view: NativeDocumentView) throws {
        try harness.type("北塔 North", at: 0, in: view)
        for line in ["Rain falls 雨夜钟声。", "Second 第二段。"] {
            try harness.type("\n", at: (view.textView.string as NSString).length, in: view)
            try harness.type(line, at: (view.textView.string as NSString).length, in: view)
        }
        view.binding.format(.heading2, range: NSRange(location: 0, length: 0))
        try wait { !view.binding.hasPendingWork }
        try require(view.binding.store.projection?.blocks.map(\.kind) == ["heading", "paragraph", "paragraph"],
            "The settings body has other blocks: \(view.binding.store.projection?.blocks.map(\.kind) ?? [])")
    }

    // MARK: (a) Every setting restyles open editors

    private static func settingsApplyToOpenEditors() throws {
        let harness = try SettingsHarness()
        defer { harness.remove() }
        // Two chapters: 钟楼 stays as a hidden tab in the left pane; 雨夜 is
        // shown in both panes.
        let hidden = try harness.open(harness.other)
        try harness.type("Other 其他。", at: 0, in: hidden)
        let left = try harness.open(harness.chapter, pane: 0)
        try writeBody(harness, left)
        let right: NativeDocumentView = try elementResult { harness.host.split(completion: $0) }
        try elementSettled(harness.host, left, right)
        let editors = [left, right, hidden]
        try require(hidden.window == nil && left.window === harness.window && right.window === harness.window,
            "The hidden tab or a pane is not where the case expects")
        let latin = try location(of: "Rain", in: left), cjk = try location(of: "雨夜", in: left)
        let second = try location(of: "Second", in: left)
        left.textView.setSelectedRange(NSRange(location: latin, length: 4))
        let revision = left.binding.state!.projection.revision, text = left.textView.string
        let canUndo = left.binding.state!.projection.canUndo

        func each(_ context: String, _ check: (NativeDocumentView, Int) throws -> Void) throws {
            for view in editors {
                let at = view === hidden ? 0 : latin
                do { try check(view, at) } catch { throw LabError.message("\(context) (\(view === hidden ? "hidden tab" : view === left ? "left pane" : "right pane")): \(error.localizedDescription)") }
            }
        }

        // Defaults at launch: the system serif at 17 pt, CJK in Songti.
        try each("Default serif") { view, at in
            try require(storedFont(view, at: at).fontName.hasPrefix(".NewYork") && storedFont(view, at: at).pointSize == 17,
                "not the 17 pt system serif: \(storedFont(view, at: at).fontName)")
        }
        try require(drawnFont(left, at: cjk) == "STSongti-SC-Regular", "CJK is not set in Songti: \(drawnFont(left, at: cjk))")
        try require(storedFont(left, at: 0).pointSize == 24 && storedFont(left, at: 0).fontName.hasPrefix(".NewYork"),
            "The heading is not the 24 pt serif")
        try require(paragraph(left, at: latin).lineSpacing == 6 && paragraph(left, at: latin).firstLineHeadIndent == 0,
            "Default line spacing or indent differs: \(paragraph(left, at: latin))")
        try require(left.textView.isContinuousSpellCheckingEnabled, "Spelling is not on by default")
        try require(attributes(left, at: cjk)[DocumentStyle.languageKey] as? String == "zh-Hans", "The manuscript language is not zh-Hans")

        let editor = harness.editor
        // 创作内容字体.
        choose(editor.fontPopup, fontSource(.systemSans))
        try each("System sans") { view, at in
            try require(storedFont(view, at: at).fontName == ".AppleSystemUIFont", "not the system sans: \(storedFont(view, at: at).fontName)")
        }
        try require(drawnFont(left, at: cjk).contains("PingFang"), "Sans CJK is not PingFang: \(drawnFont(left, at: cjk))")
        choose(editor.fontPopup, fontSource(.systemMono))
        try each("System mono") { view, at in try require(storedFont(view, at: at).isFixedPitch, "not monospaced") }
        choose(editor.fontPopup, fontSource(.systemSerif))
        try each("Serif again") { view, at in try require(storedFont(view, at: at).fontName.hasPrefix(".NewYork"), "not the serif") }
        // 系统字体 needs a family first: the popup item is disabled until then.
        try require(editor.fontPopup.item(at: fontSource(.systemCustom))?.isEnabled == false
            && editor.fontPopup.item(at: fontSource(.imported))?.isEnabled == false, "Unconfigured font sources were enabled")
        editor.familyField.stringValue = "Georgia"
        click(editor.useFamilyButton)
        try each("Georgia") { view, at in try require(storedFont(view, at: at).familyName == "Georgia", "not Georgia") }
        try require(harness.store.settings.fontSource == .systemCustom && editor.fontPopup.titleOfSelectedItem == "系统字体（Georgia）"
            && editor.fontMessage.stringValue == "已切换到系统字体“Georgia”。", "系统字体 did not follow: \(editor.fontMessage.stringValue)")
        try require(drawnFont(left, at: cjk) == "STSongti-SC-Regular", "Georgia's CJK does not fall back to Songti")
        choose(editor.fontPopup, fontSource(.systemSerif))

        // 字号: body and headings scale; the preview follows.
        slide(editor.sizeSlider, 20.3)
        try each("Size 20") { view, at in try require(storedFont(view, at: at).pointSize == 20, "size is \(storedFont(view, at: at).pointSize)") }
        try require(abs(storedFont(left, at: 0).pointSize - 20 * 24 / 17) < 0.001, "The heading did not scale with the body")
        try require(editor.sizeValue.stringValue == "20 pt" && harness.store.settings.fontSize == 20, "The size label differs")
        try require((editor.preview.textStorage?.attribute(.font, at: 0, effectiveRange: nil) as? NSFont)?.pointSize == 20,
            "The preview did not follow the size")

        // 行距: a multiple of the size, added to the face's natural line height.
        let before = paragraph(left, at: latin).lineSpacing
        slide(editor.lineHeightSlider, 1.8)
        let natural = NSLayoutManager().defaultLineHeight(for: DocumentStyle.bodyFont)
        try each("Line height 1.8") { view, at in
            try require(paragraph(view, at: at).lineSpacing == max(0, (20 * 1.8 - natural).rounded()),
                "line spacing is \(paragraph(view, at: at).lineSpacing)")
        }
        try require(paragraph(left, at: latin).lineSpacing > before && editor.lineHeightValue.stringValue == "1.80",
            "Line height did not grow")

        // 段首缩进: two characters on body paragraphs only.
        choose(editor.indentControl, 2)
        try each("Indent") { view, at in
            try require(paragraph(view, at: at).firstLineHeadIndent == 40 && paragraph(view, at: at).headIndent == 0,
                "paragraph indent is \(paragraph(view, at: at).firstLineHeadIndent)")
        }
        try require(paragraph(left, at: 0).firstLineHeadIndent == 0, "The heading was indented")

        // 手稿默认语言: CJK glyphs follow the language.
        let language = harness.settings.languagePane
        choose(language.localePopup, LabSettings.locales.firstIndex { $0.code == "ja" }!)
        try require(attributes(left, at: cjk)[DocumentStyle.languageKey] as? String == "ja"
            && drawnFont(left, at: cjk) == "HiraMinProN-W3", "Japanese did not switch to Mincho: \(drawnFont(left, at: cjk))")
        choose(language.localePopup, 0)
        try require(drawnFont(left, at: cjk) == "STSongti-SC-Regular", "Simplified Chinese did not return to Songti")

        // 拼写检查.
        language.spellcheckSwitch.state = .off; click(language.spellcheckSwitch)
        try require(editors.allSatisfy { !$0.textView.isContinuousSpellCheckingEnabled }, "Spelling stayed on")
        language.spellcheckSwitch.state = .on; click(language.spellcheckSwitch)
        try require(editors.allSatisfy { $0.textView.isContinuousSpellCheckingEnabled }, "Spelling did not return")

        // 主题: every window follows, including 设置; the hidden tab takes it when shown.
        let appearance = harness.settings.appearancePane
        choose(appearance.themeControl, 1)
        try require(dark(harness.window.effectiveAppearance) && dark(harness.settings.window!.effectiveAppearance)
            && dark(left.effectiveAppearance) && dark(right.effectiveAppearance),
            "深色 did not reach every window: main \(dark(harness.window.effectiveAppearance)), 设置 \(dark(harness.settings.window!.effectiveAppearance))")
        _ = try harness.open(harness.other, pane: 0)
        try require(hidden.window === harness.window && dark(hidden.effectiveAppearance), "The hidden tab was not dark when shown")
        _ = try harness.open(harness.chapter, pane: 0)
        left.textView.setSelectedRange(NSRange(location: latin, length: 4))
        choose(appearance.themeControl, 0)
        try require(!dark(harness.window.effectiveAppearance) && !dark(left.effectiveAppearance) && !dark(right.effectiveAppearance),
            "浅色 did not apply")
        choose(appearance.themeControl, 2)
        try require(NSApplication.shared.appearance == nil && harness.store.settings.theme == .system, "跟随系统 kept a fixed appearance")

        // 界面强调色: the selection wash and the selected tab.
        appearance.accentWell.color = NSColor(srgbRed: 0.75, green: 0.22, blue: 0.17, alpha: 1)
        click(appearance.accentWell)
        let accent = DocumentStyle.linkColor(hex: "#BF382B")!
        try require(harness.store.settings.accentColor == "#BF382B" && appearance.accentValue.stringValue == "#BF382B"
            && !appearance.accentReset.isHidden, "The accent was not stored: \(harness.store.settings.accentColor ?? "nil")")
        try require(editors.allSatisfy { ($0.textView.selectedTextAttributes[.backgroundColor] as? NSColor) == accent.withAlphaComponent(0.28) },
            "The selection did not take the accent")
        let tab = findButton("chapter-tab-\(harness.chapter.id)", in: harness.host)
        try require(tab?.contentTintColor == accent, "The selected tab did not take the accent")
        click(appearance.accentReset)
        try require(harness.store.settings.accentColor == nil && appearance.accentValue.stringValue == "跟随系统"
            && (left.textView.selectedTextAttributes[.backgroundColor] as? NSColor) == .selectedTextBackgroundColor
            && findButton("chapter-tab-\(harness.chapter.id)", in: harness.host)?.contentTintColor == nil, "恢复默认 kept the accent")

        // Restyling never touched the prose, the selection or its history.
        try require(left.textView.string == text && left.binding.state!.projection.revision == revision
            && left.binding.state!.projection.canUndo == canUndo && left.textView.selectedRange() == NSRange(location: latin, length: 4),
            "A settings change touched the text, selection or history")

        // Typing after a change takes the one-block path and matches the full reference.
        var updates: [DocumentStyle.Update] = []
        left.onStyleUpdate = { updates.append($0) }
        try harness.type("新", at: second + ("Second" as NSString).length, in: left)
        try elementSettled(harness.host, left, right)
        left.onStyleUpdate = nil
        try require(updates.first == .block(2) && !updates.contains(.full),
            "Typing after a settings change did not restyle one block: \(updates)")
        for view in [left, right] {
            try requireStyleReference(view.textView.textStorage!, view.binding.store.projection!, "typing under new settings")
        }
        left.undoProse(); try wait { !left.binding.hasPendingWork }
        try require(left.textView.string == text, "Undo after the settings change differs")

        // 还原推荐样式.
        click(editor.resetButton)
        try require(harness.store.settings.fontSize == 17 && harness.store.settings.lineHeight == 1.5
            && harness.store.settings.paragraphIndent == .none && harness.store.settings.fontSource == .systemSerif
            && harness.store.settings.systemFontFamily == "Georgia", "还原推荐样式 did not restore the defaults")
        try each("Reset") { view, at in
            try require(storedFont(view, at: at).pointSize == 17 && paragraph(view, at: at).lineSpacing == 6
                && paragraph(view, at: at).firstLineHeadIndent == 0, "not back to the defaults")
        }
        try require(editor.sizeSlider.doubleValue == 17 && editor.indentControl.selectedSegment == 0, "Controls did not follow the reset")
        try harness.close()
    }

    private static func findButton(_ identifier: String, in view: NSView) -> NSButton? {
        if view.accessibilityIdentifier() == identifier, let button = view as? NSButton { return button }
        for child in view.subviews { if let found = findButton(identifier, in: child) { return found } }
        return nil
    }

    // MARK: (b) An imported font

    private static func settingsImportedFont() throws {
        let harness = try SettingsHarness()
        defer { harness.remove() }
        let view = try harness.open(harness.chapter)
        try writeBody(harness, view)
        let latin = try location(of: "Rain", in: view), cjk = try location(of: "雨夜", in: view)
        let editor = harness.editor
        let suffix = String(UUID().uuidString.prefix(6))
        let family = "Drifting Synthetic \(suffix)"
        let source = try harness.font(family, file: "合成字体.ttf")
        var chosen = source
        editor.chooseFontFile = { done in done(chosen) }
        click(editor.importButton)
        let settings = harness.store.settings
        guard let imported = settings.importedFont, let stored = harness.store.importedFontURL else {
            throw LabError.message("The font was not imported: \(editor.fontMessage.stringValue)")
        }
        try require(settings.fontSource == .imported && imported.family == family && imported.fileName == "合成字体.ttf"
            && imported.byteLength == (try Data(contentsOf: source)).count, "The imported font was recorded differently: \(imported)")
        try require(stored.deletingLastPathComponent().standardizedFileURL == harness.root.appendingPathComponent("fonts").standardizedFileURL
            && FileManager.default.contentsEqual(atPath: stored.path, andPath: source.path),
            "The copy is not in the lab data directory: \(stored.path)")
        try require(storedFont(view, at: latin).familyName == family && drawnFont(view, at: latin).hasPrefix("DriftingSynthetic\(suffix)"),
            "Prose is not set in the imported font: \(storedFont(view, at: latin).fontName)")
        try require(drawnFont(view, at: cjk) == "STSongti-SC-Regular", "CJK did not fall back to the serif: \(drawnFont(view, at: cjk))")
        try require(editor.fontMessage.stringValue == "字体已保存在本机并应用到创作内容。" && editor.fontMessage.textColor == .secondaryLabelColor
            && editor.fontPopup.titleOfSelectedItem == "导入字体（合成字体.ttf）" && editor.importButton.title == "替换…"
            && !editor.removeFontButton.isHidden && editor.importedDetail.stringValue.hasPrefix("合成字体.ttf · "),
            "The editor pane does not show the import: \(editor.fontMessage.stringValue) / \(editor.importedDetail.stringValue)")
        // Other sources and back: the imported item stays available.
        choose(editor.fontPopup, fontSource(.systemSans))
        try require(storedFont(view, at: latin).fontName == ".AppleSystemUIFont", "Switching away from the imported font failed")
        choose(editor.fontPopup, fontSource(.imported))
        try require(storedFont(view, at: latin).familyName == family, "Switching back to the imported font failed")

        // Refusals change nothing and keep the stored copy.
        for (name, content, reason) in [("损坏.ttf", "不是字体", "无法解析这个字体文件，请确认它是有效的 Regular 或 Variable Font。"),
                                        ("说明.txt", "不是字体", "仅支持 TTF 或 OTF 字体文件。"),
                                        ("空白.otf", "", "这个字体文件是空的。")] {
            chosen = harness.sources.appendingPathComponent(name)
            try Data(content.utf8).write(to: chosen)
            click(editor.importButton)
            try require(editor.fontMessage.stringValue == reason && editor.fontMessage.textColor == .systemRed,
                "\(name) was not refused as expected: \(editor.fontMessage.stringValue)")
            try require(harness.store.settings == settings && storedFont(view, at: latin).familyName == family,
                "Refusing \(name) changed the settings or the prose font")
            try require(try FileManager.default.contentsOfDirectory(atPath: stored.deletingLastPathComponent().path) == [stored.lastPathComponent],
                "Refusing \(name) left a file in fonts/")
        }

        // 替换…: a second font replaces the copy.
        let replacementFamily = "Drifting Synthetic \(String(UUID().uuidString.prefix(6)))"
        chosen = try harness.font(replacementFamily, file: "替换字体.otf")
        click(editor.importButton)
        guard let replacement = harness.store.importedFontURL else { throw LabError.message("The replacement was not stored") }
        try require(harness.store.settings.importedFont?.family == replacementFamily && !FileManager.default.fileExists(atPath: stored.path)
            && FileManager.default.fileExists(atPath: replacement.path) && storedFont(view, at: latin).familyName == replacementFamily,
            "替换… did not replace the font and its copy")

        // 移除: the copy goes and prose returns to the system serif.
        click(editor.removeFontButton)
        try require(harness.store.settings.importedFont == nil && harness.store.settings.fontSource == .systemSerif
            && !FileManager.default.fileExists(atPath: replacement.path) && storedFont(view, at: latin).fontName.hasPrefix(".NewYork"),
            "移除 did not remove the font")
        try require(editor.fontMessage.stringValue == "已移除应用内保存的字体副本。" && editor.removeFontButton.isHidden
            && editor.fontPopup.item(at: fontSource(.imported))?.isEnabled == false && editor.importButton.title == "导入字体…",
            "The editor pane did not follow 移除")
        try harness.close()
    }

    // MARK: (c) Persistence across a cold relaunch

    private static func settingsPersistAcrossRelaunch() throws {
        let harness = try SettingsHarness()
        defer { harness.remove() }
        let view = try harness.open(harness.chapter)
        try writeBody(harness, view)
        let editor = harness.editor, appearance = harness.settings.appearancePane, language = harness.settings.languagePane
        let family = "Drifting Synthetic \(String(UUID().uuidString.prefix(6)))"
        let source = try harness.font(family, file: "持久字体.ttf")
        editor.chooseFontFile = { done in done(source) }
        click(editor.importButton)
        slide(editor.sizeSlider, 22)
        slide(editor.lineHeightSlider, 1.8)
        choose(editor.indentControl, 1)
        choose(appearance.themeControl, 1)
        appearance.accentWell.color = NSColor(srgbRed: 0.2, green: 0.5, blue: 0.3, alpha: 1)
        click(appearance.accentWell)
        language.spellcheckSwitch.state = .off; click(language.spellcheckSwitch)
        choose(language.localePopup, LabSettings.locales.firstIndex { $0.code == "zh-TW" }!)
        let settings = harness.store.settings, typography = harness.store.typography
        try require(settings.fontSource == .imported && settings.fontSize == 22 && settings.lineHeight == 1.8 && settings.paragraphIndent == .one
            && settings.theme == .dark && settings.accentColor == "#33804D" && !settings.spellcheck && settings.manuscriptLocale == "zh-TW",
            "The settings before relaunch differ: \(settings)")
        // The file lives in the lab's own data directory.
        let file = harness.root.appendingPathComponent(LabSettingsStore.fileName)
        let json = try JSONSerialization.jsonObject(with: Data(contentsOf: file)) as? [String: Any]
        try require(json?["fontSize"] as? Double == 22 && json?["theme"] as? String == "dark"
            && (json?["importedFont"] as? [String: Any])?["family"] as? String == family, "settings.json differs: \(String(describing: json))")

        try harness.relaunch()
        try require(harness.store.settings == settings && harness.store.typography == typography && harness.store.fontFallback == nil,
            "Relaunch read other settings: \(harness.store.settings) / \(harness.store.fontFallback ?? "")")
        try require(dark(NSApplication.shared.effectiveAppearance) && MacEditorPreferences.spellChecking == false
            && MacEditorPreferences.accentColor == DocumentStyle.linkColor(hex: "#33804D"), "Relaunch did not apply the theme, spelling or accent")
        let reopened = try harness.open(harness.chapter)
        let latin = try location(of: "Rain", in: reopened), cjk = try location(of: "雨夜", in: reopened)
        try require(storedFont(reopened, at: latin).familyName == family && storedFont(reopened, at: latin).pointSize == 22,
            "The reopened editor is not set in the imported font at 22 pt: \(storedFont(reopened, at: latin))")
        try require(paragraph(reopened, at: latin).firstLineHeadIndent == 22 && paragraph(reopened, at: latin).lineSpacing == typography.lineSpacing,
            "The reopened editor lost the line height or indent")
        try require(attributes(reopened, at: cjk)[DocumentStyle.languageKey] as? String == "zh-Hant"
            && drawnFont(reopened, at: cjk) == "STSongti-TC-Regular", "Traditional Chinese did not use Songti TC: \(drawnFont(reopened, at: cjk))")
        try require(!reopened.textView.isContinuousSpellCheckingEnabled && dark(reopened.effectiveAppearance)
            && (reopened.textView.selectedTextAttributes[.backgroundColor] as? NSColor) == DocumentStyle.linkColor(hex: "#33804D")!.withAlphaComponent(0.28),
            "The reopened editor lost spelling, theme or accent")
        // Every control shows the stored values.
        let newEditor = harness.editor, newAppearance = harness.settings.appearancePane, newLanguage = harness.settings.languagePane
        try require(newEditor.fontPopup.titleOfSelectedItem == "导入字体（持久字体.ttf）" && newEditor.sizeSlider.doubleValue == 22
            && newEditor.sizeValue.stringValue == "22 pt" && newEditor.lineHeightValue.stringValue == "1.80"
            && newEditor.indentControl.selectedSegment == 1 && newAppearance.themeControl.selectedSegment == 1
            && newAppearance.accentValue.stringValue == "#33804D" && newLanguage.spellcheckSwitch.state == .off
            && newLanguage.localePopup.titleOfSelectedItem == "中文（繁體） · zh-TW" && newEditor.fontMessage.isHidden,
            "The relaunched controls differ")
        try harness.close()
    }

    // MARK: (d) Fallbacks

    private static func settingsFontFallback() throws {
        let harness = try SettingsHarness()
        defer { harness.remove() }
        let view = try harness.open(harness.chapter)
        try writeBody(harness, view)
        let latin = try location(of: "Rain", in: view)
        let editor = harness.editor

        // An unknown family is refused; the font stays.
        editor.familyField.stringValue = "不存在的字体家族"
        click(editor.useFamilyButton)
        try require(editor.fontMessage.stringValue == "找不到已安装的字体“不存在的字体家族”。请确认名称，或从列表中选择。"
            && editor.fontMessage.textColor == .systemRed && harness.store.settings.fontSource == .systemSerif
            && harness.store.settings.systemFontFamily.isEmpty && storedFont(view, at: latin).fontName.hasPrefix(".NewYork"),
            "An unknown family was not refused: \(editor.fontMessage.stringValue)")

        // A system family that is later uninstalled (a process-registered
        // stand-in here) falls back after relaunch, keeping the choice.
        let installed = "Drifting Installed \(String(UUID().uuidString.prefix(6)))"
        let installedFile = try harness.font(installed, file: "installed.ttf")
        try require(LabSettingsStore.register(installedFile), "The stand-in family did not register")
        defer { LabSettingsStore.unregister(installedFile) }
        // As if installed before this session: the font list has caught up.
        try wait { LabSettingsStore.fontExists(family: installed) && NSFontManager.shared.availableFontFamilies.contains(installed) }
        editor.familyField.stringValue = installed
        click(editor.useFamilyButton)
        try require(harness.store.settings.fontSource == .systemCustom && harness.store.settings.systemFontFamily == installed
            && storedFont(view, at: latin).familyName == installed, "The installed family was not used: \(editor.fontMessage.stringValue)")
        LabSettingsStore.unregister(installedFile)
        try wait { !LabSettingsStore.fontExists(family: installed) }
        try harness.relaunch()
        let fallback = "找不到字体“\(installed)”，已改用系统衬线字体。"
        try require(harness.store.fontFallback == fallback && harness.store.typography.face == .systemSerif
            && harness.store.settings.fontSource == .systemCustom, "An uninstalled family did not fall back: \(harness.store.fontFallback ?? "none")")
        try require(harness.editor.fontMessage.stringValue == fallback && harness.editor.fontMessage.textColor == .systemRed
            && harness.editor.fontPopup.titleOfSelectedItem == "系统字体（\(installed)）", "The fallback is not shown in 设置")
        let fallen = try harness.open(harness.chapter)
        try require(storedFont(fallen, at: latin).fontName.hasPrefix(".NewYork"), "The fallback is not the system serif")

        // An imported copy that goes missing, then one that is damaged.
        let family = "Drifting Synthetic \(String(UUID().uuidString.prefix(6)))"
        let source = try harness.font(family, file: "消失字体.ttf")
        harness.editor.chooseFontFile = { done in done(source) }
        click(harness.editor.importButton)
        guard let stored = harness.store.importedFontURL else { throw LabError.message("The font to lose was not imported") }
        try require(harness.store.fontFallback == nil && storedFont(fallen, at: latin).familyName == family,
            "Importing did not replace the fallback: \(harness.store.fontFallback ?? "")")
        let message = "导入的字体“消失字体.ttf”已丢失或无法读取，已改用系统衬线字体。请重新导入。"
        for (context, damage) in [("missing", { try FileManager.default.removeItem(at: stored) }),
                                  ("damaged", { try Data("损坏".utf8).write(to: stored) })] as [(String, () throws -> Void)] {
            LabSettingsStore.unregister(stored)
            try damage()
            try harness.relaunch()
            try require(harness.store.fontFallback == message && harness.store.typography.face == .systemSerif
                && harness.store.settings.fontSource == .imported, "A \(context) copy did not fall back: \(harness.store.fontFallback ?? "none")")
            try require(harness.editor.fontMessage.stringValue == message && harness.editor.fontMessage.textColor == .systemRed,
                "The \(context) fallback is not shown in 设置")
            let page = try harness.open(harness.chapter)
            try require(storedFont(page, at: latin).fontName.hasPrefix(".NewYork"), "A \(context) copy did not fall back to the serif")
        }
        // Importing again recovers.
        harness.editor.chooseFontFile = { done in done(source) }
        click(harness.editor.importButton)
        let recovered = try harness.open(harness.chapter)
        try require(harness.store.fontFallback == nil && storedFont(recovered, at: latin).familyName == family
            && harness.editor.fontMessage.stringValue == "字体已保存在本机并应用到创作内容。", "Importing again did not recover the font")
        try harness.close()
    }

    // MARK: Synthetic font

    /// A minimal TrueType font: .notdef, then a box glyph for every
    /// printable ASCII character, named `family` (Regular).
    static func syntheticFont(family: String) -> Data {
        func u16(_ value: Int) -> [UInt8] { [UInt8((value >> 8) & 0xFF), UInt8(value & 0xFF)] }
        func u32(_ value: UInt32) -> [UInt8] { [UInt8(value >> 24), UInt8((value >> 16) & 0xFF), UInt8((value >> 8) & 0xFF), UInt8(value & 0xFF)] }
        let first = 0x20, last = 0x7E, glyphs = 1 + (last - first + 1)
        var glyf: [UInt8] = [], loca: [UInt8] = []
        for glyph in 0..<glyphs {
            loca += u16(glyf.count / 2)
            guard glyph > 1 else { continue }  // .notdef and the space are empty
            glyf += u16(1) + u16(50) + u16(0) + u16(550) + u16(700) + u16(3) + u16(0) + [1, 1, 1, 1]
            glyf += u16(50) + u16(0) + u16(500) + u16(0)
            glyf += u16(0) + u16(700) + u16(0) + u16(-700 & 0xFFFF)
        }
        loca += u16(glyf.count / 2)
        let head = u32(0x0001_0000) + u32(0x0001_0000) + u32(0) + u32(0x5F0F_3CF5) + u16(0x000B) + u16(1000)
            + [UInt8](repeating: 0, count: 16) + u16(0) + u16(0) + u16(600) + u16(700) + u16(0) + u16(8) + u16(2) + u16(0) + u16(0)
        let hhea = u32(0x0001_0000) + u16(800) + u16(-200 & 0xFFFF) + u16(0) + u16(600) + u16(0) + u16(0) + u16(550)
            + u16(1) + u16(0) + u16(0) + [UInt8](repeating: 0, count: 8) + u16(0) + u16(glyphs)
        let maxp = u32(0x0001_0000) + u16(glyphs) + u16(4) + u16(1) + u16(0) + u16(0) + u16(2) + [UInt8](repeating: 0, count: 18)
        var os2 = u16(4) + u16(600) + u16(400) + u16(5) + u16(0)
        os2 += u16(650) + u16(600) + u16(0) + u16(75) + u16(650) + u16(600) + u16(0) + u16(350) + u16(50) + u16(300)
        os2 += u16(0) + [UInt8](repeating: 0, count: 10) + u32(1) + u32(0) + u32(0) + u32(0) + Array("DRFT".utf8)
        os2 += u16(0x0040) + u16(first) + u16(last) + u16(800) + u16(-200 & 0xFFFF) + u16(0) + u16(800) + u16(200)
        os2 += u32(1) + u32(0) + u16(500) + u16(700) + u16(0) + u16(0x20) + u16(1)
        var hmtx: [UInt8] = []
        for _ in 0..<glyphs { hmtx += u16(600) + u16(50) }
        // cmap format 4: printable ASCII maps to glyphs 1…, then the end segment.
        var subtable = u16(4) + u16(0) + u16(0) + u16(4) + u16(4) + u16(1) + u16(0)
        subtable += u16(last) + u16(0xFFFF) + u16(0) + u16(first) + u16(0xFFFF) + u16((1 - first) & 0xFFFF) + u16(1) + u16(0) + u16(0)
        subtable.replaceSubrange(2..<4, with: u16(subtable.count))
        let cmap = u16(0) + u16(1) + u16(3) + u16(1) + u32(12) + subtable
        let postscript = family.filter { $0.isASCII && ($0.isLetter || $0.isNumber) }
        let names: [(Int, String)] = [(1, family), (2, "Regular"), (3, "\(postscript)-Regular-1.0"), (4, family), (6, "\(postscript)-Regular")]
        var strings: [UInt8] = [], records: [UInt8] = []
        for (id, value) in names {
            let bytes = value.utf16.flatMap { u16(Int($0)) }
            records += u16(3) + u16(1) + u16(0x0409) + u16(id) + u16(bytes.count) + u16(strings.count)
            strings += bytes
        }
        let name = u16(0) + u16(names.count) + u16(6 + records.count) + records + strings
        let post = u32(0x0003_0000) + u32(0) + u16(-100 & 0xFFFF) + u16(50) + [UInt8](repeating: 0, count: 20)
        let tables: [(String, [UInt8])] = [("OS/2", os2), ("cmap", cmap), ("glyf", glyf), ("head", head), ("hhea", hhea),
                                           ("hmtx", hmtx), ("loca", loca), ("maxp", maxp), ("name", name), ("post", post)]
        func checksum(_ bytes: [UInt8]) -> UInt32 {
            let padded = bytes + [UInt8](repeating: 0, count: (4 - bytes.count % 4) % 4)
            return stride(from: 0, to: padded.count, by: 4).reduce(UInt32(0)) { sum, at in
                sum &+ (UInt32(padded[at]) << 24 | UInt32(padded[at + 1]) << 16 | UInt32(padded[at + 2]) << 8 | UInt32(padded[at + 3]))
            }
        }
        var directory = u32(0x0001_0000) + u16(tables.count) + u16(128) + u16(3) + u16(tables.count * 16 - 128)
        var body: [UInt8] = [], headOffset = 0
        let start = 12 + tables.count * 16
        for (tag, bytes) in tables {
            if tag == "head" { headOffset = start + body.count }
            directory += Array(tag.utf8) + u32(checksum(bytes)) + u32(UInt32(start + body.count)) + u32(UInt32(bytes.count))
            body += bytes + [UInt8](repeating: 0, count: (4 - bytes.count % 4) % 4)
        }
        var font = directory + body
        font.replaceSubrange((headOffset + 8)..<(headOffset + 12), with: u32(0xB1B0_AFBA &- checksum(font)))
        return Data(font)
    }
}
