/**
 * Gather hash-validated rolling section summaries for a chapter, ready to
 * inject as `priorSections` on a BaseBlockContext.
 *
 * Validity model:
 *   - The block_section row was written with `blockSignature = hash(blockIds + each block text)`.
 *   - At read time we recompute the signature from the editor's CURRENT
 *     state. Mismatch = the user has edited at least one of the covered
 *     blocks since the summary was written → the summary is stale.
 *   - Stale rows are dropped from this turn's prompt context AND deleted
 *     from the repo / store / server (they'll be regenerated by future
 *     debounces if those blocks land in dirty again).
 *
 * This is the only consumer that calls into the editor here; capability
 * code never needs to know about signatures.
 */
import type { Editor } from '@tiptap/core';
import type { Node as PMNode } from '@tiptap/pm/model';
import loglevel from 'loglevel';
import { isBlockType } from '../extensions/block-id';
import type { PriorSectionSnippet } from '../ai/context/types';
import { computeBlockSignature } from './block-signature';
import { useDataStore } from '../../store/data-store';
import { createBlockSectionRepository } from '../../sqlite-repo/block-section-repo';
import { syncBlockSectionDelete } from '../../usecase/sync-helpers';

const log = loglevel.getLogger('copilot:prior-sections');

export interface GatherPriorSectionsInput {
  editor: Editor;
  chapterId: string;
  /**
   * Block ids the current debounce is about to scan. Sections that ONLY
   * cover these blocks are excluded from priorSections — feeding them
   * back as "prior" while their text is also in `recentText` is redundant
   * and wastes tokens. (The signature check would drop most of these
   * anyway once text actually changed, but excluding by id avoids relying
   * on that for the no-text-change case.)
   */
  dirtyBlockIds?: Iterable<string>;
}

export interface GatheredPriorSections {
  /** Valid (signature-matching) sections, oldest first. */
  sections: PriorSectionSnippet[];
}

export async function gatherPriorSections(
  input: GatherPriorSectionsInput,
): Promise<GatheredPriorSections> {
  const chapterSections = useDataStore
    .getState()
    .blockSections.filter((s) => s.chapterId === input.chapterId)
    .sort((a, b) => a.createdAt.localeCompare(b.createdAt));

  if (chapterSections.length === 0) return { sections: [] };

  const dirtySet = new Set(input.dirtyBlockIds ?? []);
  // One walk over the editor doc collects every block text the validator
  // might need (across all sections in this chapter).
  const allRelevantBlockIds = new Set<string>();
  for (const s of chapterSections) for (const id of s.blockIds) allRelevantBlockIds.add(id);
  const textsById = collectBlockTexts(input.editor, allRelevantBlockIds);

  const valid: PriorSectionSnippet[] = [];
  const stale: string[] = []; // section ids
  const repo = createBlockSectionRepository();

  for (const section of chapterSections) {
    // Skip sections that fully overlap with the current dirty batch — see
    // the input doc comment for rationale.
    if (
      dirtySet.size > 0 &&
      section.blockIds.length > 0 &&
      section.blockIds.every((id) => dirtySet.has(id))
    ) {
      continue;
    }

    const currentSignature = computeBlockSignature(
      section.blockIds,
      (id) => textsById.get(id) ?? '',
    );

    if (currentSignature === section.blockSignature) {
      valid.push({ blockIds: section.blockIds, summary: section.summary });
    } else {
      stale.push(section.id);
    }
  }

  if (stale.length > 0) {
    log.info(`[copilot:prior-sections] dropping ${stale.length} stale section(s)`);
    // Best-effort eviction. Failures are non-fatal — the row will just be
    // re-checked and dropped again next debounce.
    for (const id of stale) {
      try {
        const row = chapterSections.find((s) => s.id === id);
        await repo.delete(id);
        useDataStore.getState().removeBlockSection(id);
        if (row) syncBlockSectionDelete(id, row.projectId);
      } catch (err) {
        log.info(`[copilot:prior-sections] eviction of ${id.slice(0, 8)} failed`, err);
      }
    }
  }

  return { sections: valid };
}

function collectBlockTexts(editor: Editor, wantedIds: Set<string>): Map<string, string> {
  const out = new Map<string, string>();
  editor.state.doc.descendants((node: PMNode) => {
    if (!isBlockType(node.type.name)) return undefined;
    const id = node.attrs?.id as string | null | undefined;
    if (!id) return undefined;
    if (wantedIds.has(id)) {
      out.set(id, node.textContent.replace(/\s+/g, ' ').trim());
    }
    return false;
  });
  return out;
}
