import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import { buildDriftingAgentCapabilityManifest } from '../src/renderer/lib/agent/runtime/drifting-agent-capability-manifest';

const coreDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = path.join(
  coreDirectory,
  'docs/agent-runtime/acceptance/agent-capabilities.json',
);
const markdownPath = path.join(
  coreDirectory,
  'docs/agent-runtime/acceptance/agent-capabilities.md',
);
const repositoryDirectory = path.resolve(coreDirectory, '..');

const documentationRequirements = [
  {
    path: path.join(repositoryDirectory, 'AGENTS.md'),
    required: ['Every completed feature milestone must update', 'agent-capabilities.md'],
  },
  {
    path: path.join(coreDirectory, 'README.md'),
    required: ['agent-capabilities.md', 'CURRENT_STATUS.md', 'ROADMAP.md'],
  },
  {
    path: path.join(coreDirectory, 'docs/agent-runtime/ROADMAP.md'),
    required: [
      'A milestone is complete only when',
      'acceptance/agent-capabilities.json',
      'acceptance/agent-capabilities.md',
      'acceptance/CURRENT_STATUS.md',
    ],
  },
  {
    path: path.join(coreDirectory, 'docs/agent-runtime/acceptance/CURRENT_STATUS.md'),
    required: [
      'agent-capabilities.json',
      'agent-capabilities.md',
      '../ROADMAP.md',
      'agent:capabilities:check',
    ],
  },
] as const;

async function checkDocumentationContract(): Promise<string[]> {
  const failures: string[] = [];
  for (const requirement of documentationRequirements) {
    let contents = '';
    try {
      contents = await readFile(requirement.path, 'utf8');
    } catch {
      failures.push(`${path.relative(repositoryDirectory, requirement.path)} is missing`);
      continue;
    }
    for (const marker of requirement.required) {
      if (!contents.includes(marker)) {
        failures.push(
          `${path.relative(repositoryDirectory, requirement.path)} is missing "${marker}"`,
        );
      }
    }
    if (/\b\d+\s+of\s+\d+\s+write tools\b/i.test(contents)) {
      failures.push(
        `${path.relative(repositoryDirectory, requirement.path)} contains a hand-maintained write count`,
      );
    }
  }
  return failures;
}

function codeList(values: readonly string[]): string {
  return values.map((value) => `\`${value}\``).join(', ');
}

function renderMarkdown(manifest: ReturnType<typeof buildDriftingAgentCapabilityManifest>): string {
  const lines = [
    '# Drifting Agent capability inventory',
    '',
    '> Generated by `pnpm agent:capabilities:generate`. Do not edit by hand.',
    '',
    'This is the current built-in product composition, not a historical phase report.',
    'Runtime-discovered project MCP/plugin tools are additional and generation-bound.',
    '',
    '## Summary',
    '',
    '| Capability | Current value |',
    '| --- | ---: |',
    `| Installed built-in model tools | ${manifest.installedModelTools.total} |`,
    `| Installed reads | ${manifest.installedModelTools.read} |`,
    `| Installed writes | ${manifest.installedModelTools.write} |`,
    `| Direct catalog writes | ${manifest.directCatalogWrites.total} |`,
    `| Direct write-certified | ${manifest.directCatalogWrites.certified} |`,
    `| Direct unavailable | ${manifest.directCatalogWrites.unavailable} |`,
    `| Workspace hidden domain operations | ${manifest.workspaceFacade.hiddenDomainOperations.length} |`,
    `| Domain lifecycle contracts | ${manifest.domainCrud.totalDomains} |`,
    `| Closed domain lifecycle operations | ${manifest.domainCrud.closedLifecycleOperations} |`,
    `| Standard context window | ${manifest.product.contextWindowTokens.toLocaleString('en-US')} tokens |`,
    `| Max context request | ${manifest.product.maxContextWindowTokens.toLocaleString('en-US')} tokens |`,
    `| App concurrency cap | none |`,
    '',
    'The direct catalog count deliberately does not describe the complete user-facing',
    'write surface. The workspace facade exposes fewer natural verbs while routing',
    'certified hidden domain operations through the same durable write coordinator.',
    '',
    '## Conversation concurrency',
    '',
    `- Admission policy: \`${manifest.product.concurrency.admissionPolicy}\``,
    `- Active turn cardinality: \`${manifest.product.concurrency.activeTurnCardinality}\``,
    `- Project scope: \`${manifest.product.concurrency.projectScope}\``,
    `- Control routing: \`${manifest.product.concurrency.controlRouting}\``,
    `- Read scheduling: \`${manifest.product.concurrency.readScheduling}\``,
    `- Write scheduling: \`${manifest.product.concurrency.writeScheduling}\``,
    `- Stale-write policy: \`${manifest.product.concurrency.staleWritePolicy}\``,
    `- Yjs collaborator identity: \`${manifest.product.concurrency.yjsCollaboratorIdentity}\``,
    `- Yjs revision provenance: \`${manifest.product.concurrency.yjsRevisionProvenance}\``,
    `- Conflict attribution: \`${manifest.product.concurrency.conflictAttribution}\``,
    `- Restart behavior: \`${manifest.product.concurrency.restartBehavior}\``,
    '',
    '## Direct certified writes',
    '',
    codeList(manifest.directCatalogWrites.certifiedNames),
    '',
    '## Direct unavailable writes',
    '',
    codeList(manifest.directCatalogWrites.unavailableNames),
    '',
    '## Workspace facade',
    '',
    `Provider tools: ${codeList(manifest.workspaceFacade.providerTools)}`,
    '',
    `Hidden domain operations: ${codeList(manifest.workspaceFacade.hiddenDomainOperations)}`,
    '',
    '## Domain CRUD closure',
    '',
    '| Domain | Workspace paths | Create | Read | Update | Delete | Revert |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...manifest.domainCrud.entries.map(
      (domain) =>
        `| \`${domain.domain}\` | ${codeList(domain.workspacePaths)} | ${domain.operations.create.status} | ${domain.operations.read.status} | ${domain.operations.update.status} | ${domain.operations.delete.status} | ${domain.operations.revert.status} |`,
    ),
    '',
    '## Installed built-in tools',
    '',
    '| Name | Access | Surface | Owner | Certification |',
    '| --- | --- | --- | --- | --- |',
    ...manifest.installedModelTools.entries.map(
      (tool) =>
        `| \`${tool.name}\` | ${tool.access} | ${tool.surface} | ${tool.owner} | ${tool.certification} |`,
    ),
    '',
    '## Long-task execution contract',
    '',
    `- Default task budgets: \`${manifest.longTaskExecution.defaultTaskBudgets}\``,
    `- Continuation authorization: \`${manifest.longTaskExecution.continuationAuthorization}\``,
    `- Safe stop boundary: \`${manifest.longTaskExecution.stopBoundary}\``,
    `- Steering boundary: \`${manifest.longTaskExecution.steeringBoundary}\``,
    `- Restart behavior: \`${manifest.longTaskExecution.restartBehavior}\``,
    `- Manifest policy: \`${manifest.longTaskExecution.manifestPolicy}\``,
    `- Completion policy: \`${manifest.longTaskExecution.completionPolicy}\``,
    `- Continuation prompt visibility: \`${manifest.longTaskExecution.automaticContinuationPrompts}\``,
    `- Stagnant automatic slices before pause: ${manifest.longTaskExecution.stagnantSliceWatchdog}`,
    '',
    '## Context engineering contract',
    '',
    `- Provider profile: \`${manifest.contextEngineering.providerProfile.id}\``,
    `- Declared window: ${manifest.contextEngineering.providerProfile.contextWindowTokens.toLocaleString('en-US')} tokens`,
    `- Maximum output per provider call: ${manifest.contextEngineering.providerProfile.maxOutputTokens.toLocaleString('en-US')} tokens`,
    `- Undeclared-provider fallback: ${manifest.contextEngineering.undeclaredProviderWindowTokens.toLocaleString('en-US')} tokens`,
    `- Literary summary schema: v${manifest.contextEngineering.compaction.summarySchemaVersion}`,
    `- Exact citation kinds: ${codeList(manifest.contextEngineering.compaction.exactCitationKinds)}`,
    `- Constraint retention: \`${manifest.contextEngineering.compaction.constraintRetention}\``,
    `- Constraint conflict policy: \`${manifest.contextEngineering.compaction.conflictPolicy}\``,
    `- Evidence retrieval: \`${manifest.contextEngineering.evidenceRetrieval}\``,
    `- Result artifacts: \`${manifest.contextEngineering.resultArtifacts}\``,
    '',
    '## Author-owned writing policy',
    '',
    `- Product writing defaults: \`${manifest.authorControl.productWritingDefaults}\``,
    `- Editor context injection: \`${manifest.authorControl.editorContextInjection}\``,
    `- Content mutation scope guard: \`${manifest.authorControl.contentMutationScopeGuard}\``,
    `- Canon patch gate: \`${manifest.authorControl.canonPatchGate}\``,
    `- Project rules: \`${manifest.authorControl.projectRules}\``,
    `- Standing guidance: \`${manifest.authorControl.standingGuidance}\``,
    `- Guidance lifecycle: \`${manifest.authorControl.guidanceLifecycle}\``,
    `- Execution safety: \`${manifest.authorControl.executionSafety}\``,
    '',
    '## Provider and extension platform',
    '',
    `- Certified providers: ${manifest.providerExtensionPlatform.certifiedProviders
      .map((provider) => `\`${provider.provider}\` (${codeList(provider.models.map((model) => model.id))})`)
      .join('; ')}`,
    `- Provider reasoning profiles: ${manifest.providerExtensionPlatform.certifiedProviders
      .flatMap((provider) =>
        provider.models.map(
          (model) =>
            `\`${model.id}\` thinking=${codeList(model.thinkingModes)} effort=${
              model.efforts.length ? codeList(model.efforts) : '`unsupported`'
            } wire=\`${model.wireContract}\``,
        ),
      )
      .join('; ')}`,
    `- MCP protocol: \`${manifest.providerExtensionPlatform.mcpProtocolVersion}\``,
    `- MCP transports: ${codeList(manifest.providerExtensionPlatform.transports)}`,
    `- Stdio targets: \`${manifest.providerExtensionPlatform.stdioTargets}\``,
    `- HTTP targets: \`${manifest.providerExtensionPlatform.httpTargets}\``,
    `- Configuration: \`${manifest.providerExtensionPlatform.configuration}\``,
    `- Secrets: \`${manifest.providerExtensionPlatform.secrets}\``,
    `- Durable grants: \`${manifest.providerExtensionPlatform.grants}\``,
    `- Lifecycle: \`${manifest.providerExtensionPlatform.lifecycle}\``,
    '',
    '## Native and endurance acceptance',
    '',
    `- Mobile builds: \`${manifest.nativeEnduranceAcceptance.mobileBuilds}\``,
    `- Endurance: \`${manifest.nativeEnduranceAcceptance.endurance}\``,
    `- Cadence: \`${manifest.nativeEnduranceAcceptance.cadence}\``,
    `- Private prose: \`${manifest.nativeEnduranceAcceptance.privateProse}\``,
    '',
    '## Deferred product capabilities',
    '',
    ...manifest.deferredProductCapabilities.map((capability) => `- \`${capability}\``),
    '',
  ];
  // `lines` deliberately ends with one empty item, so join already emits the
  // canonical single trailing newline. Appending another one would create a
  // blank line at EOF and make `git diff --check` reject generated evidence.
  return lines.join('\n');
}
async function main(): Promise<void> {
  const manifest = buildDriftingAgentCapabilityManifest();
  const expected = `${JSON.stringify(manifest, null, 2)}\n`;
  const expectedMarkdown = renderMarkdown(manifest);
  const check = process.argv.slice(2).includes('--check');

  if (check) {
    let actual = '';
    let actualMarkdown = '';
    try {
      actual = await readFile(outputPath, 'utf8');
    } catch {
      // The mismatch below gives one stable remediation command.
    }
    try {
      actualMarkdown = await readFile(markdownPath, 'utf8');
    } catch {
      // The mismatch below gives one stable remediation command.
    }
    const documentationFailures = await checkDocumentationContract();
    if (
      actual !== expected ||
      actualMarkdown !== expectedMarkdown ||
      documentationFailures.length > 0
    ) {
      process.stderr.write(
        'Agent capability evidence is stale. Run `pnpm agent:capabilities:generate`.\n',
      );
      if (documentationFailures.length > 0) {
        process.stderr.write(`${documentationFailures.join('\n')}\n`);
      }
      process.exitCode = 1;
    } else {
      process.stdout.write('Agent capability evidence is current.\n');
    }
  } else {
    await Promise.all([
      writeFile(outputPath, expected, 'utf8'),
      writeFile(markdownPath, expectedMarkdown, 'utf8'),
    ]);
    process.stdout.write(
      `${path.relative(coreDirectory, outputPath)} and ${path.relative(
        coreDirectory,
        markdownPath,
      )} updated.\n`,
    );
  }
}

void main().catch((error: unknown) => {
  process.stderr.write(
    `${error instanceof Error ? (error.stack ?? error.message) : String(error)}\n`,
  );
  process.exitCode = 1;
});
