import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { getTableColumns, getTableName } from 'drizzle-orm';
import * as drizzleSchema from '../src/renderer/schema/drizzle';
import { SYNC_DOMAIN_MANIFEST_V1 } from '../src/renderer/sync/protocol/domain-manifest';
import {
  validateDomainManifestAgainstSchema,
  type PersistedTableInventory,
} from '../src/renderer/sync/protocol/domain-manifest-schema';

const root = process.cwd();
const outputDirectory = path.join(root, 'docs/sync-engine/acceptance');
const jsonPath = path.join(outputDirectory, 'sync-domain-manifest.json');
const markdownPath = path.join(outputDirectory, 'sync-domain-manifest.md');
const checkOnly = process.argv.includes('--check');

function inspectDrizzleSchema(): readonly PersistedTableInventory[] {
  const inventory: PersistedTableInventory[] = [];
  for (const exportedValue of Object.values(drizzleSchema)) {
    try {
      const table = getTableName(exportedValue as Parameters<typeof getTableName>[0]);
      const columns = Object.values(
        getTableColumns(exportedValue as Parameters<typeof getTableColumns>[0]),
      ).map((column) => column.name);
      inventory.push({ table, columns: columns.sort() });
    } catch {
      // Ignore non-table schema exports.
    }
  }
  return inventory.sort((left, right) => (left.table < right.table ? -1 : 1));
}

const inventory = inspectDrizzleSchema();
const issues = validateDomainManifestAgainstSchema(SYNC_DOMAIN_MANIFEST_V1, inventory);
if (issues.length > 0) {
  console.error(`Sync domain manifest drifted from Drizzle schema (${issues.length} issue(s)):`);
  for (const issue of issues) console.error(`- ${issue}`);
  process.exit(1);
}

const schemaFingerprint = createHash('sha256')
  .update(JSON.stringify(inventory))
  .digest('hex');
const expandedTables = SYNC_DOMAIN_MANIFEST_V1.tables.map((table) => ({
  table: table.table,
  scope: table.scope,
  disposition: table.disposition,
  reason: table.reason,
  fields: Object.entries(table.fields)
    .sort(([left], [right]) => (left < right ? -1 : 1))
    .map(([field, policy]) => ({ field, ...policy })),
}));
const fieldPolicies = expandedTables.flatMap((table) => table.fields);
const classCounts = Object.fromEntries(
  ['authored', 'crdt', 'derived', 'device-local', 'secret', 'transport'].map((classification) => [
    classification,
    fieldPolicies.filter((field) => field.classification === classification).length,
  ]),
);
const evidence = {
  protocol: SYNC_DOMAIN_MANIFEST_V1.protocol,
  version: SYNC_DOMAIN_MANIFEST_V1.version,
  schemaSource: 'src/renderer/schema/drizzle.ts',
  schemaSha256: schemaFingerprint,
  gate: 'Every Drizzle table and column must have one explicit class and non-empty reason.',
  summary: {
    tableCount: expandedTables.length,
    fieldCount: fieldPolicies.length,
    includedTableCount: expandedTables.filter((table) => table.disposition === 'include').length,
    excludedTableCount: expandedTables.filter((table) => table.disposition === 'exclude').length,
    classCounts,
  },
  tables: expandedTables,
};

const json = `${JSON.stringify(evidence, null, 2)}\n`;
const markdown = `${[
  '# Sync domain manifest evidence',
  '',
  '> Generated by `pnpm exec tsx scripts/generate-sync-domain-manifest.ts`. Do not edit by hand.',
  '',
  `- Protocol: \`${evidence.protocol}\` v${evidence.version}`,
  `- Drizzle schema SHA-256: \`${evidence.schemaSha256}\``,
  `- Tables: ${evidence.summary.tableCount} (${evidence.summary.includedTableCount} included, ${evidence.summary.excludedTableCount} excluded)`,
  `- Fields: ${evidence.summary.fieldCount}`,
  `- Classes: ${Object.entries(classCounts)
    .map(([classification, count]) => `${classification}=${count}`)
    .join(', ')}`,
  '',
  '| Table | Scope | Sync | Fields | Decision |',
  '| --- | --- | --- | ---: | --- |',
  ...expandedTables.map(
    (table) =>
      `| \`${table.table}\` | \`${table.scope}\` | \`${table.disposition}\` | ${table.fields.length} | ${table.reason.replaceAll('|', '\\|')} |`,
  ),
  '',
  '## Reproduce',
  '',
  '```bash',
  'pnpm exec tsx scripts/generate-sync-domain-manifest.ts --check',
  'pnpm exec vitest run src/renderer/sync/protocol/domain-manifest.test.ts',
  '```',
].join('\n')}\n`;

function checkFile(filePath: string, expected: string): boolean {
  try {
    return readFileSync(filePath, 'utf8') === expected;
  } catch {
    return false;
  }
}

if (checkOnly) {
  const stale = [
    !checkFile(jsonPath, json) ? path.relative(root, jsonPath) : null,
    !checkFile(markdownPath, markdown) ? path.relative(root, markdownPath) : null,
  ].filter((value): value is string => value !== null);
  if (stale.length > 0) {
    console.error(`Sync domain manifest evidence is missing or stale: ${stale.join(', ')}`);
    process.exit(1);
  }
  console.log(
    `Sync domain manifest evidence is current (${evidence.summary.tableCount} tables, ${evidence.summary.fieldCount} fields).`,
  );
} else {
  mkdirSync(outputDirectory, { recursive: true });
  writeFileSync(jsonPath, json);
  writeFileSync(markdownPath, markdown);
  console.log(`Wrote ${path.relative(root, jsonPath)} and ${path.relative(root, markdownPath)}.`);
}
