import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import {
  DEV_CLI_MODEL_CAPABILITIES,
  DEV_CLI_PROVIDER_TOOLS,
  DEV_CLI_TABLE_MODEL_COVERAGE,
} from '../src/dev-cli/manifest';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputDirectory = path.join(root, 'docs/dev-cli/acceptance');
const jsonPath = path.join(outputDirectory, 'cli-capabilities.json');
const markdownPath = path.join(outputDirectory, 'cli-capabilities.md');

const payload = {
  schemaVersion: 1,
  generatedFrom: [
    'src/dev-cli/manifest.ts',
    'src/renderer/lib/agent/runtime/drifting-workspace-tool-contract.ts',
    'src/renderer/schema/drizzle.ts',
  ],
  models: DEV_CLI_MODEL_CAPABILITIES,
  tables: DEV_CLI_TABLE_MODEL_COVERAGE,
  providerTools: DEV_CLI_PROVIDER_TOOLS,
};

const json = `${JSON.stringify(payload, null, 2)}\n`;
const markdown = `${[
  '# Drifting Dev CLI Capability Inventory',
  '',
  '> Generated by `pnpm dev:cli:capabilities`. Do not edit by hand.',
  '',
  `- Schema tables accounted for: ${Object.keys(DEV_CLI_TABLE_MODEL_COVERAGE).length}`,
  `- Domain read tools: ${DEV_CLI_PROVIDER_TOOLS.read.length}`,
  `- Domain write tools: ${DEV_CLI_PROVIDER_TOOLS.write.length}`,
  '',
  '| Model | Scope | Authority | Coverage | Commands | Boundary |',
  '| --- | --- | --- | --- | --- | --- |',
  ...DEV_CLI_MODEL_CAPABILITIES.map(
    (model) =>
      `| ${model.name} | ${model.scope} | ${model.authority} | ${model.coverage} | ${model.commands.join('<br>') || '—'} | ${model.note.replaceAll('|', '\\|')} |`,
  ),
  '',
  '## Exact table accountability',
  '',
  '| SQLite table | CLI model |',
  '| --- | --- |',
  ...Object.entries(DEV_CLI_TABLE_MODEL_COVERAGE).map(
    ([table, model]) => `| ${table} | ${model} |`,
  ),
].join('\n')}\n`;

async function checkFile(file: string, expected: string): Promise<void> {
  let actual = '';
  try {
    actual = await readFile(file, 'utf8');
  } catch {
    /* reported as drift below */
  }
  if (actual !== expected)
    throw new Error(`${path.relative(root, file)} is stale; run pnpm dev:cli:capabilities`);
}

async function main(): Promise<void> {
  if (process.argv.includes('--check')) {
    await checkFile(jsonPath, json);
    await checkFile(markdownPath, markdown);
    return;
  }
  await mkdir(outputDirectory, { recursive: true });
  await Promise.all([writeFile(jsonPath, json), writeFile(markdownPath, markdown)]);
  process.stdout.write(
    `Generated ${path.relative(root, jsonPath)} and ${path.relative(root, markdownPath)}\n`,
  );
}

void main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
