import {
  DRIFTING_DOMAIN_READ_TOOLS,
  DRIFTING_DOMAIN_WRITE_TOOLS,
} from '../renderer/lib/agent/runtime/drifting-workspace-tool-contract';
import type { CliModelCapability } from './types';

const WORKSPACE_CALL = ['workspace call'];
const RESOURCE_CRUD = [
  'workspace resource list',
  'workspace resource get',
  'workspace resource create',
  'workspace resource update',
  'workspace resource delete',
];
const RESOURCE_READ = ['workspace resource list', 'workspace resource get'];

/**
 * Machine-readable boundary for the developer CLI. Every persisted product
 * model is named here, including models intentionally kept out of generic
 * CRUD. This prevents a new table from silently becoming an unsafe back door.
 */
export const DEV_CLI_MODEL_CAPABILITIES: readonly CliModelCapability[] = [
  {
    name: 'project',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'full_lifecycle',
    commands: [...WORKSPACE_CALL, ...RESOURCE_CRUD],
    table: 'project',
    note: 'Authored project facts use the canonical Agent domain runtime; project creation and deletion use explicit resource commands.',
  },
  {
    name: 'node',
    scope: 'workspace',
    authority: 'yjs_sqlite',
    coverage: 'full_lifecycle',
    commands: WORKSPACE_CALL,
    table: 'book_node',
    note: 'Chapters and free-floating inspirations use canonical domain tools; prose always commits through Yjs.',
  },
  {
    name: 'node_content',
    scope: 'workspace',
    authority: 'yjs_sqlite',
    coverage: 'workflow_only',
    commands: WORKSPACE_CALL,
    table: 'node_content',
    note: 'content_json is only a seed/cache projection and is never exposed as generic CRUD.',
  },
  {
    name: 'storyline',
    scope: 'workspace',
    authority: 'yjs_sqlite',
    coverage: 'full_lifecycle',
    commands: WORKSPACE_CALL,
    table: 'storylines',
    note: 'Canonical storyline domain tools, including authored body prose.',
  },
  {
    name: 'node_storyline_link',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'full_lifecycle',
    commands: WORKSPACE_CALL,
    table: 'node_storyline_link',
    note: 'Membership and primary-storyline invariants are enforced by domain commands.',
  },
  {
    name: 'element_category',
    scope: 'workspace',
    authority: 'yjs_sqlite',
    coverage: 'full_lifecycle',
    commands: WORKSPACE_CALL,
    table: 'element_category',
    note: 'Canonical element-category lifecycle and prose body.',
  },
  {
    name: 'element',
    scope: 'workspace',
    authority: 'yjs_sqlite',
    coverage: 'full_lifecycle',
    commands: WORKSPACE_CALL,
    table: 'element',
    note: 'Canonical element lifecycle, facts, aliases and authored prose.',
  },
  {
    name: 'element_patch',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'full_lifecycle',
    commands: WORKSPACE_CALL,
    table: 'element_patch',
    note: 'Sanctioned canon evolution channel with durable Agent receipts.',
  },
  {
    name: 'comment',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'full_lifecycle',
    commands: WORKSPACE_CALL,
    table: 'comment',
    note: 'Unified note/todo/comment lifecycle through the canonical domain runtime.',
  },
  {
    name: 'comment_action',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'workflow_only',
    commands: RESOURCE_READ,
    table: 'comment_action',
    note: 'Actions are workflow evidence; only inspect through the CLI.',
  },
  {
    name: 'relation_type',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'full_lifecycle',
    commands: WORKSPACE_CALL,
    table: 'entity_relation_type',
    note: 'Endpoint-kind and orientation validation stay in the domain runtime.',
  },
  {
    name: 'relation_type_endpoint_kind',
    scope: 'workspace',
    authority: 'derived',
    coverage: 'derived_rebuild',
    commands: WORKSPACE_CALL,
    table: 'entity_relation_type_endpoint_kind',
    note: 'Rebuilt atomically from relation-type definitions; no independent CRUD.',
  },
  {
    name: 'entity_relation',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'full_lifecycle',
    commands: WORKSPACE_CALL,
    table: 'entity_relation',
    note: 'Typed cross-entity relations with endpoint validation.',
  },
  {
    name: 'inline_mention',
    scope: 'ops',
    authority: 'derived',
    coverage: 'derived_rebuild',
    commands: ['ops inspect'],
    table: 'inline_mention',
    note: 'Derived from authored prose; never generic CRUD.',
  },
  {
    name: 'book_act',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'full_lifecycle',
    commands: RESOURCE_CRUD,
    table: 'book_act',
    note: 'Act boundary rows; null start_order means book head.',
  },
  {
    name: 'drift_group',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'full_lifecycle',
    commands: RESOURCE_CRUD,
    table: 'drift_group',
    note: 'Nested inspiration folders with project-scoped lifecycle.',
  },
  {
    name: 'timeline_marker',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'full_lifecycle',
    commands: RESOURCE_CRUD,
    table: 'timeline_marker',
    note: 'Narrative-axis pins; drift references remain explicit.',
  },
  {
    name: 'library_item',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'full_lifecycle',
    commands: RESOURCE_CRUD,
    table: 'library_item',
    note: 'Project material metadata; file bytes are not synthesized by CRUD.',
  },
  {
    name: 'project_asset',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'workflow_only',
    commands: RESOURCE_READ,
    table: 'project_asset',
    note: 'Upload lifecycle owns asset writes; CLI inspection is safe.',
  },
  {
    name: 'asset_upload_job',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'workflow_only',
    commands: RESOURCE_READ,
    table: 'asset_upload_job',
    note: 'Resumable upload workflow state; not generic CRUD.',
  },
  {
    name: 'block_section',
    scope: 'ops',
    authority: 'derived',
    coverage: 'derived_rebuild',
    commands: ['ops inspect'],
    table: 'block_section',
    note: 'Copilot-derived rolling summaries.',
  },
  {
    name: 'agent_conversation',
    scope: 'agent',
    authority: 'sqlite',
    coverage: 'workflow_only',
    commands: ['agent turn', 'agent review'],
    table: 'agent_conversation',
    note: 'Conversation lifecycle is owned by Agent transport.',
  },
  {
    name: 'agent_runtime',
    scope: 'agent',
    authority: 'sqlite',
    coverage: 'inspect_reconcile',
    commands: ['ops inspect'],
    note: 'Sessions, turns, messages, events, tool calls, checkpoints, tasks and receipts are append-only runtime evidence.',
  },
  {
    name: 'agent_memory',
    scope: 'workspace',
    authority: 'sqlite',
    coverage: 'full_lifecycle',
    commands: WORKSPACE_CALL,
    table: 'agent_memory',
    note: 'Project-scoped durable memories through certified domain commands.',
  },
  {
    name: 'agent_working_memory',
    scope: 'agent',
    authority: 'sqlite',
    coverage: 'workflow_only',
    commands: ['agent turn'],
    table: 'agent_working_memory',
    note: 'Long-turn document is owned by the Agent working-memory runtime.',
  },
  {
    name: 'agent_mcp_server',
    scope: 'agent',
    authority: 'sqlite',
    coverage: 'workflow_only',
    commands: [],
    table: 'agent_mcp_server',
    note: 'MCP configuration remains owned by the App runtime; credentials stay in secure storage.',
  },
  {
    name: 'agent_permission_grant',
    scope: 'agent',
    authority: 'sqlite',
    coverage: 'inspect_reconcile',
    commands: ['agent turn', 'agent review', 'ops inspect'],
    table: 'agent_permission_grant',
    note: 'Durable exact grants are policy evidence, not generic records.',
  },
  {
    name: 'entity_snapshot_history',
    scope: 'ops',
    authority: 'sqlite',
    coverage: 'workflow_only',
    commands: ['ops inspect'],
    table: 'entity_snapshot_history',
    note: 'Restore uses the history-restore Yjs origin and guarded workflow.',
  },
  {
    name: 'yjs_updates_and_snapshots',
    scope: 'ops',
    authority: 'yjs_sqlite',
    coverage: 'inspect_reconcile',
    commands: ['ops inspect'],
    note: 'Append-only CRDT authority; never row-level CRUD.',
  },
  {
    name: 'yjs_revision_and_provenance',
    scope: 'ops',
    authority: 'yjs_sqlite',
    coverage: 'inspect_reconcile',
    commands: ['ops inspect'],
    note: 'Revision/provenance evidence is append-only and runtime-owned.',
  },
  {
    name: 'local_sync_mutation',
    scope: 'ops',
    authority: 'sqlite',
    coverage: 'inspect_reconcile',
    commands: ['ops inspect'],
    table: 'local_sync_mutation',
    note: 'Outbox is written with domain transactions and never manually CRUDed.',
  },
  {
    name: 'server_project_graph',
    scope: 'server',
    authority: 'server',
    coverage: 'full_lifecycle',
    commands: ['server request'],
    note: 'Authenticated real HTTP API for projects, categories, storylines, nodes, content, memberships, elements and sync.',
  },
  {
    name: 'server_account_preferences_subscription_export',
    scope: 'server',
    authority: 'server',
    coverage: 'workflow_only',
    commands: ['server request'],
    note: 'Account, preferences, subscription and export use the real server workflows.',
  },
  {
    name: 'secure_credentials',
    scope: 'agent',
    authority: 'secret_store',
    coverage: 'excluded',
    commands: [],
    note: 'BYOK and MCP secrets never enter stdout, JSON fixtures or SQLite CRUD.',
  },
  {
    name: 'retired_shadow_arc_goal_evolve',
    scope: 'agent',
    authority: 'derived',
    coverage: 'excluded',
    commands: [],
    note: 'Retired products and unshipped Ambient Editor are intentionally absent.',
  },
] as const;

export const DEV_CLI_PROVIDER_TOOLS = {
  read: DRIFTING_DOMAIN_READ_TOOLS,
  write: DRIFTING_DOMAIN_WRITE_TOOLS,
} as const;

/** Exact schema-table accountability, checked against Drizzle in tests. */
export const DEV_CLI_TABLE_MODEL_COVERAGE: Readonly<Record<string, string>> = {
  project: 'project',
  element_category: 'element_category',
  project_asset: 'project_asset',
  asset_upload_job: 'asset_upload_job',
  storylines: 'storyline',
  book_node: 'node',
  drift_group: 'drift_group',
  node_content: 'node_content',
  element: 'element',
  node_storyline_link: 'node_storyline_link',
  element_patch: 'element_patch',
  block_section: 'block_section',
  entity_relation_type: 'relation_type',
  entity_relation_type_endpoint_kind: 'relation_type_endpoint_kind',
  entity_relation: 'entity_relation',
  inline_mention: 'inline_mention',
  comment: 'comment',
  comment_action: 'comment_action',
  library_item: 'library_item',
  agent_conversation: 'agent_conversation',
  agent_runtime_session: 'agent_runtime',
  agent_runtime_turn: 'agent_runtime',
  agent_runtime_message: 'agent_runtime',
  agent_runtime_event: 'agent_runtime',
  agent_runtime_tool_call: 'agent_runtime',
  agent_runtime_read_receipt: 'agent_runtime',
  agent_runtime_read_observation: 'agent_runtime',
  agent_runtime_result_blob: 'agent_runtime',
  agent_runtime_result_artifact: 'agent_runtime',
  agent_runtime_write_effect: 'agent_runtime',
  agent_runtime_element_patch_receipt: 'agent_runtime',
  agent_runtime_entity_write_receipt: 'agent_runtime',
  agent_runtime_write_expectation: 'agent_runtime',
  agent_runtime_write_review: 'agent_runtime',
  agent_runtime_write_review_block: 'agent_runtime',
  agent_runtime_checkpoint: 'agent_runtime',
  agent_runtime_task: 'agent_runtime',
  agent_runtime_task_chapter_manifest: 'agent_runtime',
  agent_runtime_task_step: 'agent_runtime',
  agent_runtime_task_constraint: 'agent_runtime',
  agent_runtime_task_command: 'agent_runtime',
  agent_memory: 'agent_memory',
  agent_working_memory: 'agent_working_memory',
  book_act: 'book_act',
  timeline_marker: 'timeline_marker',
  agent_mcp_server: 'agent_mcp_server',
  agent_permission_grant: 'agent_permission_grant',
  entity_snapshot_history: 'entity_snapshot_history',
  yjs_updates: 'yjs_updates_and_snapshots',
  yjs_snapshots: 'yjs_updates_and_snapshots',
  yjs_document_revision: 'yjs_revision_and_provenance',
  yjs_document_revision_provenance: 'yjs_revision_and_provenance',
  yjs_prose_command_receipt: 'yjs_revision_and_provenance',
  yjs_sync_cursor: 'yjs_updates_and_snapshots',
  local_sync_mutation: 'local_sync_mutation',
};

export function capabilityForModel(name: string): CliModelCapability | undefined {
  return DEV_CLI_MODEL_CAPABILITIES.find((item) => item.name === name);
}

export function resourceCapability(name: string): CliModelCapability {
  const capability = capabilityForModel(name);
  if (!capability?.table) throw new Error(`Unknown CLI resource: ${name}`);
  if (!capability.commands.some((command) => command.startsWith('workspace resource'))) {
    throw new Error(`Resource ${name} is ${capability.coverage} and has no generic CRUD surface`);
  }
  return capability;
}
