/**
 * Sync protocol v1 domain classification.
 *
 * This file intentionally has no database, provider, Tauri, or network imports.
 * `domain-manifest.test.ts` compares it with the live Drizzle schema so a table
 * or column cannot enter the project database without an explicit decision.
 */

export const SYNC_DOMAIN_FIELD_CLASSES = [
  'authored',
  'crdt',
  'derived',
  'device-local',
  'secret',
  'transport',
  'extension',
] as const;

export type SyncDomainFieldClass = (typeof SYNC_DOMAIN_FIELD_CLASSES)[number];

export type SyncDomainFieldDisposition = 'include' | 'exclude';

export type SyncDomainTableScope =
  | 'project-root'
  | 'project-direct'
  | 'project-via-reference'
  | 'global';

export interface SyncDomainFieldPolicy {
  readonly classification: SyncDomainFieldClass;
  readonly disposition: SyncDomainFieldDisposition;
  readonly reason: string;
}

export interface SyncDomainTablePolicy {
  readonly table: string;
  readonly scope: SyncDomainTableScope;
  readonly disposition: SyncDomainFieldDisposition;
  readonly reason: string;
  readonly fields: Readonly<Record<string, SyncDomainFieldPolicy>>;
}

interface FieldGroup {
  readonly classification: SyncDomainFieldClass;
  readonly reason: string;
  readonly names: readonly string[];
}

interface TableInput {
  readonly table: string;
  readonly scope: SyncDomainTableScope;
  readonly disposition: SyncDomainFieldDisposition;
  readonly reason: string;
  readonly groups: readonly FieldGroup[];
}

const INCLUDED_FIELD_CLASSES = new Set<SyncDomainFieldClass>(['authored', 'crdt']);

function group(
  classification: SyncDomainFieldClass,
  reason: string,
  ...names: readonly string[]
): FieldGroup {
  return { classification, reason, names };
}

function defineTable(input: TableInput): SyncDomainTablePolicy {
  const fields: Record<string, SyncDomainFieldPolicy> = {};
  for (const fieldGroup of input.groups) {
    if (fieldGroup.reason.trim().length === 0) {
      throw new Error(`${input.table}: field classification reason must not be empty`);
    }
    for (const name of fieldGroup.names) {
      if (fields[name]) throw new Error(`${input.table}.${name}: duplicate manifest entry`);
      fields[name] = {
        classification: fieldGroup.classification,
        disposition: INCLUDED_FIELD_CLASSES.has(fieldGroup.classification) ? 'include' : 'exclude',
        reason: fieldGroup.reason,
      };
    }
  }
  return {
    table: input.table,
    scope: input.scope,
    disposition: input.disposition,
    reason: input.reason,
    fields,
  };
}

const authoredIdentity = 'Stable identity or authored domain state required to reconstruct the project.';
const derivedClock =
  'Projection of the winning change-set clock; it is rebuilt locally and is not merge authority.';
const fractionalRankProjection =
  'Numeric order is a query/UI rank rebuilt from the protocol v1 Rocicorp fractional position key plus the entity-ID UTF-8 bytewise tie-break; it never creates a wire key.';
const runtimeState =
  'Agent execution, review, receipt, session, or diagnostic state is intentionally device-local in sync v1.';

const tables: SyncDomainTablePolicy[] = [
  defineTable({
    table: 'workspace_projection_clock', scope: 'project-direct', disposition: 'exclude',
    reason: 'Rebuildable local renderer invalidation coverage, never authored state or a sync cursor.',
    groups: [group('derived', 'SQLite trigger-owned workspace read coverage; a fresh reader captures the full project.', 'project_id', 'epoch', 'revision', 'retained_after')],
  }),
  defineTable({
    table: 'workspace_projection_change', scope: 'project-direct', disposition: 'exclude',
    reason: 'Bounded local renderer invalidation hints, rebuilt by complete workspace capture after coverage loss.',
    groups: [group('derived', 'Actual row-change identities only; no prose, credentials, or author merge authority.', 'project_id', 'collection', 'entity_id', 'revision', 'replacement_revision')],
  }),
  defineTable({
    table: 'project',
    scope: 'project-root',
    disposition: 'include',
    reason: 'The project is the authored root of one independently synchronized SyncGeneration.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'name',
        'summary',
      ),
      group(
        'derived',
        'Whole-array KV JSON is a temporary projection; protocol v1 requires stable ordered KV entry identities.',
        'kv_json',
        'storyline_template_kv_json',
      ),
      group(
        'device-local',
        'The local account association is rebound on each installation and must not be restored as authored content.',
        'user_id',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'entity_kv_entry',
    scope: 'project-direct',
    disposition: 'include',
    reason:
      'Stable KV entry identities and values are the authored authority behind project, template, storyline and element JSON projections.',
    groups: [
      group(
        'authored',
        'Each row has stable identity and explicit polymorphic ownership; lifecycle, LWW clocks and order are carried by reducer state.',
        'id',
        'project_id',
        'owner_kind',
        'owner_id',
        'namespace',
        'key',
        'value',
      ),
    ],
  }),
  defineTable({
    table: 'element_category',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Element category definitions, templates, and layout are authored project state.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'name',
        'element_template_json',
        'color',
        'project_id',
        'layout_mode',
        'grid_x',
        'grid_y',
        'deleted_at',
      ),
      group(
        'crdt',
        'The category body is a local Yjs projection or checkpoint seed-only body; it never enters a change-set field or lifecycle seed.',
        'content_json',
      ),
      group(
        'derived',
        'Whole-array KV template JSON is replaced by stable ordered KV entry identities before provider activation.',
        'element_template_kv_json',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'project_asset',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Immutable source metadata and owner references are authored; provider delivery is separate transport state.',
    groups: [
      group(
        'authored',
        'Stable asset identity and immutable verified source metadata are required by checkpoints and blob bindings.',
        'id',
        'project_id',
        'kind',
        'source_mime',
        'source_size_bytes',
        'source_sha256',
        'width',
        'height',
      ),
      group('derived', derivedClock, 'created_at'),
    ],
  }),
  defineTable({
    table: 'storylines',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Storylines, templates, membership order, and lifecycle are authored project state.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'project_id',
        'name',
        'color',
        'summary',
        'node_content_template_json',
        'deleted_at',
      ),
      group(
        'crdt',
        'The storyline body is a local Yjs projection or checkpoint seed-only body; it never enters a change-set field or lifecycle seed.',
        'content_json',
      ),
      group(
        'derived',
        fractionalRankProjection,
        'order_key',
      ),
      group(
        'derived',
        'Whole-array KV JSON is a projection of stable KV entries and their fractional order registers.',
        'kv_json',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'book_node',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Chapter and drift identity, structure, ordering, placement, and lifecycle are authored state.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'title',
        'summary',
        'book_order',
        'narrative_order',
        'project_id',
        'writing_status',
        'kind',
        'drift_group_id',
        'deleted_at',
        'position_x',
        'position_y',
      ),
      group(
        'derived',
        'Canonical prose metrics are recomputed from authoritative Yjs state and their basis is local verification evidence.',
        'word_count',
        'word_count_basis_kind',
        'word_count_basis_hash',
        'word_count_basis_revision',
        'word_count_basis_server_seq',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'drift_group',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Drift hierarchy and order are authored project organization.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'project_id',
        'name',
        'parent_group_id',
        'color',
      ),
      group(
        'derived',
        fractionalRankProjection,
        'sort_order',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'node_content',
    scope: 'project-via-reference',
    disposition: 'include',
    reason: 'Node prose is Yjs state; outline and plot-grid JSON are rebuildable projections in protocol v1.',
    groups: [
      group(
        'crdt',
        'The node identity selects the prose document; content_json is only a local projection or checkpoint seed-only body, never a change-set field or lifecycle seed.',
        'node_id',
        'content_json',
      ),
      group(
        'derived',
        'Outline and plot-grid JSON are projections, not protocol merge authority.',
        'outline_json',
        'plot_grid_json',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'plot_grid_document',
    scope: 'project-via-reference',
    disposition: 'include',
    reason:
      'One stable per-node Plot Grid document owns the atomic cell-size tuple.',
    groups: [
      group(
        'authored',
        'Document identity, node ownership, and the size tuple reconstruct the normalized grid without plot_grid_json.',
        'id',
        'node_id',
        'cell_width',
        'cell_height',
      ),
    ],
  }),
  defineTable({
    table: 'plot_grid_row',
    scope: 'project-via-reference',
    disposition: 'include',
    reason: 'Stable row identity, LWW label, and ordered position are Plot Grid authority.',
    groups: [
      group(
        'authored',
        'Rows retain stable identity and explicit document ownership; reducer metadata carries lifecycle and winning clocks.',
        'id',
        'document_id',
        'position_key',
        'label',
      ),
    ],
  }),
  defineTable({
    table: 'plot_grid_column',
    scope: 'project-via-reference',
    disposition: 'include',
    reason:
      'Stable column identity, LWW label, and ordered position are Plot Grid authority.',
    groups: [
      group(
        'authored',
        'Columns retain stable identity and explicit document ownership; reducer metadata carries lifecycle and winning clocks.',
        'id',
        'document_id',
        'position_key',
        'label',
      ),
    ],
  }),
  defineTable({
    table: 'plot_grid_cell',
    scope: 'project-via-reference',
    disposition: 'include',
    reason: 'A stable coordinate identity and LWW value are the sparse Plot Grid cell authority.',
    groups: [
      group(
        'authored',
        'Cell identity binds one document row and column; reducer metadata carries lifecycle and the winning value clock.',
        'id',
        'document_id',
        'row_id',
        'column_id',
        'value',
      ),
    ],
  }),
  defineTable({
    table: 'element',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Elements, category membership, facts, aliases, asset binding, and lifecycle are authored state.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'project_id',
        'category_id',
        'name',
        'summary',
        'group_name',
        'portrait_asset_id',
        'deleted_at',
      ),
      group(
        'crdt',
        'The element body is a local Yjs projection or checkpoint seed-only body; it never enters a change-set field or lifecycle seed.',
        'content_json',
      ),
      group(
        'derived',
        'Whole-array KV and alias JSON are projections of stable KV entries and normalized OR-set tags.',
        'kv_json',
        'aliases_json',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'node_storyline_link',
    scope: 'project-via-reference',
    disposition: 'include',
    reason: 'Storyline membership and the explicit primary register are authored relationships.',
    groups: [group('authored', authoredIdentity, 'node_id', 'storyline_id', 'is_primary')],
  }),
  defineTable({
    table: 'element_patch',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Canon evolution patches and their anchors, content, order, and lifecycle are authored state.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'project_id',
        'element_id',
        'source_node_id',
        'source_block_id',
        'source_block_text',
        'text_anchor_json',
        'invalidated_at',
        'title',
        'content_json',
      ),
      group(
        'derived',
        fractionalRankProjection,
        'order_key',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'block_section',
    scope: 'project-direct',
    disposition: 'exclude',
    reason: 'Block sections and summaries are rebuildable analysis projections over prose.',
    groups: [
      group(
        'derived',
        'Every block-section field is regenerated from authoritative prose and analysis results.',
        'id',
        'project_id',
        'chapter_id',
        'block_ids_json',
        'block_hashes_json',
        'summary',
        'source',
        'created_at',
        'updated_at',
      ),
    ],
  }),
  defineTable({
    table: 'entity_relation_type',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Relation definitions and semantic roles are authored project schema.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'project_id',
        'name',
        'normalized_name',
        'description',
        'orientation',
        'system_key',
        'locked',
        'source_role',
        'target_role',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'entity_relation_type_endpoint_kind',
    scope: 'project-via-reference',
    disposition: 'include',
    reason: 'Allowed endpoint kinds are authored parts of a relation-type definition.',
    groups: [group('authored', authoredIdentity, 'relation_type_id', 'side', 'entity_kind')],
  }),
  defineTable({
    table: 'entity_relation',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Relations and their typed endpoints are authored graph state.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'project_id',
        'from_kind',
        'from_id',
        'to_kind',
        'to_id',
        'relation_type_id',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'inline_mention',
    scope: 'project-direct',
    disposition: 'exclude',
    reason: 'Inline mentions are reconstructed by indexing authoritative editor documents.',
    groups: [
      group(
        'derived',
        'Every inline-mention coordinate is a rebuildable prose index projection.',
        'id',
        'project_id',
        'from_kind',
        'from_id',
        'from_block_id',
        'from_spans_json',
        'to_kind',
        'to_id',
        'created_at',
        'updated_at',
      ),
    ],
  }),
  defineTable({
    table: 'comment',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Manual, Copilot, and Agent comments share one authored anchor and resolution model.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'project_id',
        'kind',
        'target_kind',
        'target_id',
        'target_block_id',
        'anchor_json',
        'author_kind',
        'author_id',
        'author_name',
        'body_json',
        'status',
        'priority',
        'source',
        'metadata_json',
        'target_block_ids_json',
        'resolved_at',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'comment_action',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Typed comment accept/reject actions and their settled result are authored decisions.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'project_id',
        'comment_id',
        'kind',
        'label',
        'payload_json',
        'status',
        'result_json',
        'created_by_kind',
        'created_by_id',
        'applied_at',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'library_item',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Library text, URL, binary metadata, notes, asset binding, and ordering are authored state.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'project_id',
        'title',
        'kind',
        'asset_id',
        'external_url',
        'body_json',
        'notes_json',
      ),
      group(
        'derived',
        fractionalRankProjection,
        'order_key',
      ),
      group(
        'derived',
        'External preview imagery is a network/cache projection and is never portable authored state.',
        'preview_image_url',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'agent_memory',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Durable author-facing Agent memory is explicitly included in sync v1.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'project_id',
        'kind',
        'body',
        'target_kind',
        'target_id',
        'target_block_id',
        'source',
        'origin_ref',
        'status',
        'supersedes_id',
        'deleted_at',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'agent_working_memory',
    scope: 'project-direct',
    disposition: 'exclude',
    reason: 'Working memory is ephemeral Agent execution context and is explicitly excluded from sync v1.',
    groups: [
      group(
        'device-local',
        'Every working-memory field belongs to the local runtime and compaction lifecycle.',
        'project_id',
        'content_md',
        'revision',
        'approx_tokens',
        'updated_by',
        'last_compacted_at',
        'deleted_at',
        'created_at',
        'updated_at',
      ),
    ],
  }),
  defineTable({
    table: 'book_act',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Act identity, optional book-head or finite boundary, display properties, and drift binding are authored state.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'project_id',
        'name',
        'color',
        'start_order',
        'drift_node_id',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'timeline_marker',
    scope: 'project-direct',
    disposition: 'include',
    reason: 'Timeline markers and their optional drift bindings are authored project state.',
    groups: [
      group(
        'authored',
        authoredIdentity,
        'id',
        'project_id',
        'narrative_order',
        'label',
        'drift_node_id',
      ),
      group('derived', derivedClock, 'created_at', 'updated_at'),
    ],
  }),
  defineTable({
    table: 'entity_snapshot_history',
    scope: 'project-direct',
    disposition: 'exclude',
    reason: 'Historical snapshots are local retention projections around Yjs snapshot moments.',
    groups: [
      group(
        'derived',
        'Snapshot history is rebuilt or thinned locally and is not current authored state.',
        'id',
        'project_id',
        'entity_kind',
        'entity_id',
        'state_blob',
        'content_json',
        'meta_json',
        'created_at',
      ),
    ],
  }),
  defineTable({
    table: 'yjs_updates',
    scope: 'project-via-reference',
    disposition: 'include',
    reason: 'Append-only Yjs updates are authoritative prose CRDT state.',
    groups: [
      group(
        'crdt',
        'Document identity, update identity, and binary Yjs update are required for CRDT convergence.',
        'id',
        'document_id',
        'update_blob',
      ),
      group('derived', derivedClock, 'created_at'),
    ],
  }),
  defineTable({
    table: 'yjs_snapshots',
    scope: 'project-via-reference',
    disposition: 'include',
    reason: 'Full Yjs state is authoritative checkpoint or seed state for a prose document.',
    groups: [
      group(
        'crdt',
        'Document identity and binary full-state update are required to restore CRDT truth.',
        'document_id',
        'state_blob',
      ),
      group('derived', derivedClock, 'updated_at'),
    ],
  }),
  defineTable({
    table: 'yjs_document_revision',
    scope: 'project-via-reference',
    disposition: 'exclude',
    reason: 'Document revisions are local concurrency/projection counters, not CRDT content.',
    groups: [
      group(
        'derived',
        'Revision and timestamp are regenerated as local Yjs persistence is materialized.',
        'document_id',
        'revision',
        'updated_at',
      ),
    ],
  }),
  defineTable({
    table: 'yjs_document_revision_provenance',
    scope: 'project-via-reference',
    disposition: 'exclude',
    reason: 'Revision provenance is device-local Agent and editing audit evidence.',
    groups: [
      group(
        'device-local',
        'Provenance references local sessions, turns, calls, and revision counters.',
        'document_id',
        'revision',
        'source_kind',
        'agent_session_id',
        'agent_turn_id',
        'agent_call_id',
        'created_at',
      ),
    ],
  }),
  defineTable({
    table: 'yjs_prose_command_receipt',
    scope: 'project-via-reference',
    disposition: 'exclude',
    reason: 'Prose command receipts enforce local idempotency and revision safety only.',
    groups: [
      group(
        'device-local',
        'Receipt identities, revision bases, hashes, and vectors describe a local command execution.',
        'id',
        'command_id',
        'direction',
        'document_id',
        'source_kind',
        'base_revision',
        'committed_revision',
        'base_state_vector',
        'base_state_hash',
        'result_state_vector',
        'result_state_hash',
        'update_hash',
        'update_id',
        'created_at',
      ),
    ],
  }),
];

tables.push(
  defineTable({ table: 'agent_chat_binding', scope: 'project-via-reference', disposition: 'exclude', reason: 'Owned by the isolated Agent chat extension, never the project v1 wire.', groups: [group('device-local', 'Agent chat extension storage; project v1 excludes these fields.', 'conversation_id', 'local_owner', 'session_id', 'exported_ordinal', 'seeded_through')] }),
  defineTable({ table: 'agent_chat_branch', scope: 'project-direct', disposition: 'exclude', reason: 'Owned by the isolated Agent chat extension, never the project v1 wire.', groups: [group('extension', 'Agent chat extension storage; project v1 excludes these fields.', 'id', 'project_id', 'root_id', 'parent_branch_id', 'fork_turn_id', 'head_turn_id', 'title', 'title_clock', 'deleted_at', 'created_at', 'updated_at', 'readiness')] }),
  defineTable({ table: 'agent_chat_cursor', scope: 'global', disposition: 'exclude', reason: 'Owned by the isolated Agent chat extension, never the project v1 wire.', groups: [group('device-local', 'Agent chat extension storage; project v1 excludes these fields.', 'id', 'cursor', 'backfill_complete')] }),
  defineTable({ table: 'agent_chat_delivery', scope: 'global', disposition: 'exclude', reason: 'Owned by the isolated Agent chat extension, never the project v1 wire.', groups: [group('device-local', 'Agent chat extension storage; project v1 excludes these fields.', 'scope_id', 'object_id', 'remote_id', 'state', 'detail')] }),
  defineTable({ table: 'agent_chat_object', scope: 'project-direct', disposition: 'exclude', reason: 'Owned by the isolated Agent chat extension, never the project v1 wire.', groups: [group('extension', 'Agent chat extension storage; project v1 excludes these fields.', 'id', 'project_id', 'branch_id', 'kind', 'body_json', 'hash', 'created_at')] }),
  defineTable({ table: 'agent_chat_queue', scope: 'project-via-reference', disposition: 'exclude', reason: 'Owned by the isolated Agent chat extension, never the project v1 wire.', groups: [group('device-local', 'Agent chat extension storage; project v1 excludes these fields.', 'conversation_id', 'revision')] }),
);

const runtimeTables: Readonly<Record<string, readonly string[]>> = {
  agent_conversation: [
    'id',
    'project_id',
    'title',
    'sdk_session_id',
    'runtime_session_id',
    'mode',
    'messages_json',
    'deleted_at',
    'created_at',
    'updated_at',
  ],
  agent_runtime_session: [
    'id',
    'project_id',
    'route_kind',
    'conversation_id',
    'goal_run_id',
    'chapter_id',
    'provider',
    'model',
    'provider_epoch',
    'status',
    'created_at',
    'updated_at',
    'ended_at',
  ],
  agent_runtime_turn: [
    'id',
    'session_id',
    'ordinal',
    'status',
    'prompt_message_id',
    'accepted_at',
    'started_at',
    'ended_at',
    'error_code',
    'error_message',
    'updated_at',
  ],
  agent_runtime_message: [
    'id',
    'session_id',
    'turn_id',
    'ordinal',
    'role',
    'status',
    'content_json',
    'created_at',
    'completed_at',
  ],
  agent_runtime_event: [
    'event_id',
    'session_id',
    'turn_id',
    'seq',
    'schema_version',
    'event_type',
    'payload_json',
    'wall_time_ms',
    'created_at',
  ],
  agent_runtime_tool_call: [
    'id',
    'session_id',
    'turn_id',
    'call_id',
    'name',
    'access',
    'status',
    'idempotency_key',
    'arguments_json',
    'result_json',
    'error_code',
    'created_at',
    'started_at',
    'completed_at',
  ],
  agent_runtime_read_receipt: [
    'id',
    'project_id',
    'session_id',
    'turn_id',
    'tool_call_id',
    'call_id',
    'tool_name',
    'tool_access',
    'idempotency_key',
    'result_blob',
    'result_hash',
    'created_at',
  ],
  agent_runtime_read_observation: [
    'id',
    'receipt_id',
    'project_id',
    'session_id',
    'turn_id',
    'tool_call_id',
    'ordinal',
    'entity_kind',
    'entity_id',
    'revision',
    'state_vector',
    'state_hash',
    'created_at',
  ],
  agent_runtime_result_blob: [
    'content_hash',
    'content_blob',
    'byte_count',
    'char_count',
    'created_at',
  ],
  agent_runtime_result_artifact: [
    'ref',
    'project_id',
    'session_id',
    'turn_id',
    'tool_call_id',
    'call_id',
    'tool_name',
    'tool_access',
    'idempotency_key',
    'arguments_json',
    'content_hash',
    'created_at',
  ],
  agent_runtime_write_effect: [
    'id',
    'project_id',
    'route_kind',
    'conversation_id',
    'goal_run_id',
    'chapter_id',
    'session_id',
    'turn_id',
    'tool_call_id',
    'call_id',
    'tool_name',
    'tool_access',
    'idempotency_key',
    'authorization_kind',
    'authorization_request_id',
    'authorization_arguments_hash',
    'authorized_at',
    'phase',
    'arguments_json',
    'expected_revision_json',
    'observed_revision_json',
    'preimage_json',
    'forward_json',
    'inverse_json',
    'reversibility',
    'effect_json',
    'result_json',
    'error_code',
    'error_message',
    'claimed_at',
    'confirmed_at',
    'mutation_started_at',
    'effect_committed_at',
    'result_committed_at',
    'uncertain_at',
    'failed_at',
    'declined_at',
    'updated_at',
  ],
  agent_runtime_element_patch_receipt: [
    'id',
    'effect_id',
    'command_id',
    'direction',
    'project_id',
    'session_id',
    'tool_name',
    'patch_id',
    'expected_revision',
    'result_revision',
    'postimage_json',
    'postimage_hash',
    'created_at',
  ],
  agent_runtime_entity_write_receipt: [
    'id',
    'effect_id',
    'command_id',
    'direction',
    'project_id',
    'session_id',
    'tool_name',
    'entity_kind',
    'entity_id',
    'expected_revision',
    'result_revision',
    'preimage_json',
    'preimage_hash',
    'postimage_json',
    'postimage_hash',
    'created_at',
  ],
  agent_runtime_write_expectation: [
    'id',
    'effect_id',
    'project_id',
    'session_id',
    'write_turn_id',
    'write_tool_call_id',
    'observation_id',
    'read_receipt_id',
    'read_turn_id',
    'read_tool_call_id',
    'entity_kind',
    'entity_id',
    'expected_revision',
    'expected_state_vector',
    'expected_state_hash',
    'created_at',
  ],
  agent_runtime_write_review: [
    'id',
    'effect_id',
    'session_id',
    'turn_id',
    'tool_call_id',
    'status',
    'decision_note_json',
    'revert_effect_json',
    'error_code',
    'error_message',
    'created_at',
    'accepted_at',
    'rejected_at',
    'revert_started_at',
    'settled_at',
    'updated_at',
  ],
  agent_runtime_write_review_block: [
    'review_id',
    'effect_id',
    'block_id',
    'ordinal',
    'status',
    'decision_note_json',
    'revert_effect_json',
    'error_code',
    'error_message',
    'created_at',
    'revert_started_at',
    'settled_at',
    'updated_at',
  ],
  agent_runtime_checkpoint: [
    'id',
    'session_id',
    'through_turn_ordinal',
    'message_count',
    'context_json',
    'context_hash',
    'created_at',
  ],
  agent_runtime_task: [
    'id',
    'project_id',
    'session_id',
    'objective',
    'scope_kind',
    'work_kind',
    'status',
    'revision',
    'created_at',
    'updated_at',
    'ended_at',
  ],
  agent_runtime_task_chapter_manifest: [
    'task_id',
    'project_id',
    'session_id',
    'ordinal',
    'name',
    'resolved_chapter_id',
  ],
  agent_runtime_task_step: [
    'id',
    'task_id',
    'project_id',
    'session_id',
    'ordinal',
    'title',
    'work_kind',
    'target_kind',
    'target_name',
    'resolved_target_id',
    'status',
    'result_note',
    'result_ref',
    'review_result_json',
    'created_at',
    'updated_at',
    'started_at',
    'completed_at',
  ],
  agent_runtime_task_constraint: [
    'id',
    'task_id',
    'project_id',
    'session_id',
    'body',
    'source',
    'status',
    'superseded_by_id',
    'created_at',
    'updated_at',
    'settled_at',
  ],
  agent_runtime_task_command: [
    'idempotency_key',
    'project_id',
    'session_id',
    'turn_id',
    'tool_call_id',
    'call_id',
    'tool_name',
    'tool_access',
    'task_id',
    'arguments_hash',
    'result_json',
    'created_at',
  ],
};

for (const [table, names] of Object.entries(runtimeTables)) {
  tables.push(
    defineTable({
      table,
      scope:
        table === 'agent_runtime_result_blob'
          ? 'global'
          : names.includes('project_id')
            ? 'project-direct'
            : 'project-via-reference',
      disposition: 'exclude',
      reason: runtimeState,
      groups: [group('device-local', runtimeState, ...names)],
    }),
  );
}

const syncTransportTables: Readonly<
  Record<
    string,
    {
      readonly scope: SyncDomainTableScope;
      readonly fields: readonly string[];
      readonly secretFields?: readonly string[];
    }
  >
> = {
  sync_app_authority: {
    scope: 'global',
    fields: [
      'id',
      'mode',
      'generation',
      'transition_state',
      'target_mode',
      'attempt_id',
      'updated_at',
    ],
  },
  sync_provider_account: {
    scope: 'global',
    fields: [
      'id',
      'singleton_key',
      'authority_id',
      'provider_kind',
      'authority_generation',
      'account_subject_id',
      'created_at',
      'updated_at',
    ],
    secretFields: ['credential_secret_ref'],
  },
  sync_generation: {
    scope: 'project-direct',
    fields: [
      'sync_generation_id',
      'project_id',
      'project_sync_id',
      'generation_number',
      'protocol_version',
      'domain_schema_version',
      'status',
      'created_at',
      'updated_at',
      'retired_at',
      'purged_at',
    ],
  },
  sync_generation_purge: {
    scope: 'project-via-reference',
    fields: [
      'sync_generation_id',
      'hlc_wall_ms',
      'hlc_counter',
      'writer_id',
      'writer_epoch',
      'device_seq',
      'change_set_id',
      'mutation_index',
    ],
  },
  sync_provider_binding: {
    scope: 'project-via-reference',
    fields: [
      'sync_generation_id',
      'provider_account_id',
      'provider_namespace',
      'provider_generation_ref',
      'state',
      'connected_at',
      'updated_at',
      'last_pull_success_at',
      'last_publish_success_at',
      'last_converged_at',
    ],
  },
  sync_generation_writer_state: {
    scope: 'project-via-reference',
    fields: [
      'sync_generation_id',
      'writer_id',
      'writer_epoch',
      'installation_id',
      'next_device_seq',
      'hlc_wall_ms',
      'hlc_counter',
      'created_at',
      'updated_at',
      'retired_at',
    ],
  },
  sync_change_set: {
    scope: 'project-direct',
    fields: [
      'change_set_id',
      'project_id',
      'project_sync_id',
      'sync_generation_id',
      'writer_id',
      'writer_epoch',
      'device_seq',
      'hlc_wall_ms',
      'hlc_counter',
      'protocol_version',
      'payload_version',
      'mutation_count',
      'payload_sha256',
      'encoded_bytes',
      'origin',
      'apply_state',
      'created_at',
      'applied_at',
    ],
  },
  sync_mutation: {
    scope: 'project-via-reference',
    fields: [
      'change_set_id',
      'mutation_index',
      'target_family',
      'target_kind',
      'target_id',
      'incarnation',
      'action',
      'payload_version',
      'payload_cbor',
      'payload_sha256',
    ],
  },
  sync_apply_receipt: {
    scope: 'project-via-reference',
    fields: [
      'change_set_id',
      'sync_generation_id',
      'source_object_id',
      'mutation_count',
      'state_sha256',
      'applied_at',
    ],
  },
  sync_field_clock: {
    scope: 'project-via-reference',
    fields: [
      'sync_generation_id',
      'target_kind',
      'target_id',
      'incarnation',
      'field_key',
      'hlc_wall_ms',
      'hlc_counter',
      'writer_id',
      'writer_epoch',
      'device_seq',
      'mutation_index',
      'change_set_id',
    ],
  },
  sync_set_tag: {
    scope: 'project-via-reference',
    fields: [
      'sync_generation_id',
      'owner_kind',
      'owner_id',
      'incarnation',
      'set_key',
      'value_key',
      'add_tag',
      'value_cbor',
      'add_change_set_id',
      'add_mutation_index',
      'removed_by_change_set_id',
      'removed_by_mutation_index',
    ],
  },
  sync_order_register: {
    scope: 'project-via-reference',
    fields: [
      'sync_generation_id',
      'list_kind',
      'owner_id',
      'entity_id',
      'incarnation',
      'position_key',
      'hlc_wall_ms',
      'hlc_counter',
      'writer_id',
      'writer_epoch',
      'device_seq',
      'mutation_index',
      'change_set_id',
    ],
  },
  sync_entity_lifecycle: {
    scope: 'project-via-reference',
    fields: [
      'sync_generation_id',
      'entity_kind',
      'entity_id',
      'incarnation',
      'state',
      'hlc_wall_ms',
      'hlc_counter',
      'writer_id',
      'writer_epoch',
      'device_seq',
      'mutation_index',
      'change_set_id',
    ],
  },
  sync_frontier: {
    scope: 'project-via-reference',
    fields: [
      'sync_generation_id',
      'writer_id',
      'writer_epoch',
      'received_seq',
      'applied_seq',
      'published_seq',
      'segment_head_sha256',
      'updated_at',
    ],
  },
  sync_frontier_gap: {
    scope: 'project-via-reference',
    fields: [
      'id',
      'sync_generation_id',
      'writer_id',
      'writer_epoch',
      'lane',
      'first_seq',
      'last_seq',
      'state',
      'observed_at',
      'resolved_at',
    ],
  },
  sync_segment: {
    scope: 'project-via-reference',
    fields: [
      'segment_id',
      'sync_generation_id',
      'writer_id',
      'writer_epoch',
      'first_seq',
      'last_seq',
      'change_set_count',
      'previous_segment_sha256',
      'segment_sha256',
      'required_blob_ids_cbor',
      'local_object_id',
      'state',
      'created_at',
      'published_at',
    ],
  },
  sync_remote_object: {
    scope: 'project-via-reference',
    fields: [
      'id',
      'sync_generation_id',
      'provider_object_id',
      'logical_key_id',
      'object_kind',
      'stored_sha256',
      'size_bytes',
      'provider_etag',
      'provider_version',
      'observed_cursor',
      'first_observed_at',
      'last_observed_at',
      'removed_at',
    ],
  },
  sync_cursor: {
    scope: 'project-via-reference',
    fields: [
      'sync_generation_id',
      'provider_epoch',
      'committed_cursor',
      'pending_base_cursor',
      'pending_page_token',
      'inventory_complete',
      'updated_at',
    ],
  },
  sync_transfer: {
    scope: 'project-via-reference',
    fields: [
      'transfer_id',
      'sync_generation_id',
      'direction',
      'object_kind',
      'logical_key_id',
      'local_object_id',
      'remote_object_id',
      'expected_stored_sha256',
      'total_bytes',
      'transferred_bytes',
      'state',
      'attempt_count',
      'next_attempt_at',
      'last_error_code',
      'created_at',
      'updated_at',
      'completed_at',
    ],
    secretFields: ['session_secret_ref'],
  },
  sync_local_object: {
    scope: 'project-via-reference',
    fields: [
      'id',
      'sync_generation_id',
      'object_kind',
      'logical_key_id',
      'storage_ref',
      'stored_sha256',
      'content_sha256',
      'size_bytes',
      'codec',
      'state',
      'created_at',
      'verified_at',
    ],
  },
  sync_checkpoint: {
    scope: 'project-via-reference',
    fields: [
      'checkpoint_id',
      'sync_generation_id',
      'kind',
      'protocol_version',
      'domain_schema_version',
      'frontier_cbor',
      'content_sha256',
      'logical_key_id',
      'local_object_id',
      'size_bytes',
      'change_set_count',
      'state',
      'created_at',
      'verified_at',
      'published_at',
    ],
  },
  sync_blob_state: {
    scope: 'project-via-reference',
    fields: [
      'sync_generation_id',
      'blob_id',
      'asset_id',
      'logical_key_id',
      'content_sha256',
      'size_bytes',
      'mime',
      'local_object_id',
      'local_state',
      'remote_state',
      'verified_at',
      'updated_at',
    ],
  },
  sync_restore_attempt: {
    scope: 'project-via-reference',
    fields: [
      'attempt_id',
      'source_sync_generation_id',
      'target_project_id',
      'source_checkpoint_id',
      'state',
      'staging_ref',
      'validation_code',
      'activation_receipt',
      'error_code',
      'created_at',
      'updated_at',
      'completed_at',
    ],
  },
  sync_connect_attempt: {
    scope: 'global',
    fields: [
      'attempt_id',
      'kind',
      'target_mode',
      'authority_generation',
      'target_account_subject_id',
      'state',
      'error_code',
      'created_at',
      'updated_at',
      'completed_at',
    ],
    secretFields: ['target_credential_secret_ref'],
  },
  sync_connect_generation_attempt: {
    scope: 'project-via-reference',
    fields: [
      'attempt_id',
      'source_sync_generation_id',
      'target_sync_generation_id',
      'source_checkpoint_id',
      'commit_marker_object_id',
      'activation_receipt',
      'state',
      'error_code',
      'created_at',
      'updated_at',
      'activated_at',
    ],
  },
  sync_conflict: {
    scope: 'project-via-reference',
    fields: [
      'conflict_id',
      'sync_generation_id',
      'kind',
      'target_kind',
      'target_id',
      'incarnation',
      'change_set_id',
      'mutation_index',
      'details_cbor',
      'state',
      'resolution_cbor',
      'created_at',
      'resolved_at',
    ],
  },
  sync_quarantined_object: {
    scope: 'project-via-reference',
    fields: [
      'quarantine_id',
      'sync_generation_id',
      'remote_object_id',
      'local_object_id',
      'reason',
      'observed_protocol',
      'observed_version',
      'stored_sha256',
      'size_bytes',
      'state',
      'created_at',
      'resolved_at',
    ],
  },
};

const syncTransportReason =
  'SyncEngine journal, reducer metadata, frontier, durable transfer, or recovery state is protocol machinery, not authored domain content.';

for (const [table, policy] of Object.entries(syncTransportTables)) {
  tables.push(
    defineTable({
      table,
      scope: policy.scope,
      disposition: 'exclude',
      reason: syncTransportReason,
      groups: [
        group('transport', syncTransportReason, ...policy.fields),
        ...(policy.secretFields
          ? [
              group(
                'secret' as const,
                'Only an opaque native secure-storage reference may be persisted; the referenced secret never enters SQLite or sync objects.',
                ...policy.secretFields,
              ),
            ]
          : []),
      ],
    }),
  );
}

tables.push(
  defineTable({
    table: 'agent_mcp_server',
    scope: 'project-direct',
    disposition: 'exclude',
    reason: 'MCP configuration, health, and credentials are local Agent extension state.',
    groups: [
      group(
        'device-local',
        'MCP identity, public configuration, policy, health, and discovery are installation-local.',
        'id',
        'project_id',
        'name',
        'transport',
        'enabled',
        'command',
        'args_json',
        'cwd',
        'public_env_json',
        'url',
        'public_headers_json',
        'tool_policy_json',
        'config_revision',
        'health_status',
        'health_message',
        'server_info_json',
        'discovered_tools_json',
        'last_checked_at',
        'last_connected_at',
        'created_at',
        'updated_at',
      ),
      group(
        'secret',
        'Environment and header secrets must remain in local secure storage/config and never enter sync objects.',
        'secret_env_json',
        'secret_headers_json',
      ),
    ],
  }),
  defineTable({
    table: 'agent_permission_grant',
    scope: 'project-direct',
    disposition: 'exclude',
    reason: 'Exact MCP grants are installation-local security decisions and are never synchronized.',
    groups: [
      group(
        'device-local',
        'Every grant field is bound to a local session, tool definition, or revocation decision.',
        'id',
        'project_id',
        'session_id',
        'scope',
        'source_kind',
        'source_id',
        'provider_tool_name',
        'remote_tool_name',
        'access',
        'arguments_hash',
        'tool_definition_revision',
        'source_config_revision',
        'status',
        'created_at',
        'last_used_at',
        'revoked_at',
        'revoked_reason',
      ),
    ],
  }),
);

export const SYNC_DOMAIN_MANIFEST_V1 = Object.freeze({
  protocol: 'drifting.sync.domain-manifest' as const,
  version: 1 as const,
  tables: Object.freeze([...tables].sort((left, right) => (left.table < right.table ? -1 : 1))),
});

export function getSyncDomainTablePolicy(table: string): SyncDomainTablePolicy | undefined {
  return SYNC_DOMAIN_MANIFEST_V1.tables.find((entry) => entry.table === table);
}
